"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\classifier.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.classifier
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueAndUpVersionRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueAndUpVersionRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueBeforeVersionRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBeforeVersionRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueBlockAndUnitNumbersNOrMoreRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBlockAndUnitNumbersNOrMoreRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueBlockAndUnitNumbersRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBlockAndUnitNumbersRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueBlockNameRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBlockNameRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueBUHRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBUHRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueClassificationContext.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueClassificationContext
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueClassificationResult.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueClassificationResult
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueClassifier.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueClassifier
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueFaultLimitRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueFaultLimitRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueFlavour.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueFlavour
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueFlavourAFactory.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueFlavourAFactory
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueFlavourBFactory.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueFlavourBFactory
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueFlavourCFactory.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueFlavourCFactory
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueFlavourFactory.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueFlavourFactory
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueGoodVolumeRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGoodVolumeRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueHaveFaultRelationshipsRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueHaveFaultRelationshipsRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueHaveFaultRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueHaveFaultRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueHaveTipLoopRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueHaveTipLoopRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueLayerToUnitRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueLayerToUnitRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueLGRIDRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueLGRIDRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueMultiBlockRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueMultiBlockRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueNoGlobalsRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueNoGlobalsRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueOneBUPerURule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueOneBUPerURule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueParameterizedSurfaceRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueParameterizedSurfaceRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescuePassRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePassRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescuePreV30ValidatorRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePreV30ValidatorRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueRefIdRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueRefIdRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueReporter.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueReporter
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueSplitNodesRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSplitNodesRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueStandardModelPropertyGroupingRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueStandardModelPropertyGroupingRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueStandardPropertyGroupingRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueStandardPropertyGroupingRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueStreamReporter.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueStreamReporter
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueUnitNameRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueUnitNameRule
"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\RescueVersionRule.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueVersionRule
