"C:\Program Files\Java\jdk1.5.0_04\bin\javac" -classpath . org\Rescue\rjni\*.java
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagInt
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueBlockUnit
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueEdgeSet
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueGeobodyPart
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueHistory
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueHistoryObject
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescuePolyLine
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescuePolyLineStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueProperty
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescuePropertyGroup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueSection
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueStairSteppedFault
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueSurfaceCell
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueSurfaceToGrid
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueTriangleVertex
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueTrimLoop
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueWellboreCell
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueWellboreSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cNameValuePair
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueArrayFragment
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueBlock
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueBlockUnit
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueBlockUnitHorizonSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueBlockUnitSide
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueDataContainer
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueEdgeSet
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueEdgeSetStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueEventDescr
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueFaultIntersection
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueGeobody
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueGeobodyPart
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueGeobodySurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueGeobodyVolume
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueGeometry
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueGeometryUnit
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueGridAxis
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueHistory
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueHorizon
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueIJSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueInterfaceSurfaceDesc
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueLookup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueMacroVolume
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueModelPropertyGroup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescuePoint
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescuePolyLine
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescuePolyLineNode
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescuePolyLineNodeBUG
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescuePolyLineNodeUV
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescuePolyLineNodeUVT
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescuePolyLineStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueProperty
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescuePropertyGroup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueReferenceSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueReservoir
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueSection
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueSOctTreeNode
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueStairSteppedFault
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueSurfaceCell
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueSurfaceToGrid
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueTimeStepGroup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueTriangleFace
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueTriangleVertex
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueTrimEdge
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueTrimLoop
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueTrimLoopStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueTrimVertex
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueUnit
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueWellbore
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueWellboreCell
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueWellboreProperty
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueWellboreSampling
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueWellboreSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetRescueWireframe
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cSetString
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.myHeaders
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RCH2DArray
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RCH3DArray
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RCHf2DArray
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RCHf3DArray
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArray
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArray2dVector
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArray3dVector
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayByte
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayDouble
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFloat
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFragment
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFragment2dVector
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFragment3dVector
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFragmentByte
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFragmentFloat
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFragmentDouble
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFragmentInt
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayFragmentShort
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayInt
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueArrayShort
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBitArray
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBlock
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBlockUnit
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBlockUnitHorizonSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueBlockUnitSide
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueColor
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueColorTable
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueColorTableList
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueContext
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueCoordinateLine
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueCoordinatePolyLine
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueCoordinateSystem
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueCoordinateSystemAxis
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueDataContainer
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueEdgeSet
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueEdgeSetStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueEventDescr
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueFaultIntersection
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGeobody
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGeobodyPart
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGeobodySurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGeobodyVolume
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGeometry
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGeometryUnit
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGrid
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGridAxis
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueHistory
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueHistoryObject
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueHorizon
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueIdTree
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueIdTreeNode
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueIJSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueInterfaceSurfaceDesc
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueLogicalOrder
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueLogicalOrderEntry
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueLookup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueLookupItem
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueLookupString
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueLookupTable
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueMacroVolume
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueModel
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueModelPropertyGroup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueObject
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueParametricLGRMap
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePillar
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePoint
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePolyLine
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePolyLineNode
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePolyLineNodeBUG
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePolyLineNodeUV
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePolyLineNodeUVT
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePolyLineStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueProgressReporter
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueProperty
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescuePropertyGroup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueQuadrupletArray
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueRadialGrid
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueReferenceSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueReservoir
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSection
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSOctTreeNode
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSplineCoef
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSplitLine
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSplitPoint
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueStairSteppedFault
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSurfaceCell
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueSurfaceToGrid
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTimeStepGroup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTriangleFace
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTriangleVertex
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTriangulatedSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTrimEdge
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTrimLoop
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTrimLoopStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTrimVertex
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTrimVertexStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTripletArray
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTruncation
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueUnit
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueUnstructuredGrid
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueVertex
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWellbore
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWellboreCell
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWellboreProperty
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWellboreSampling
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWellboreSurface
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWireframe
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWireframeCallBack
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWireframeOwner
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueWireframeStub
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueZStack
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGeometryPropertyList
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueGeometryLGRList
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.cBagRescueTimeStepGroup
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueTimeStepManager
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueUOM
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueDocumentList
"C:\Program Files\Java\jdk1.5.0_04\bin\javah" -classpath . org.Rescue.rjni.RescueDocument
