/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueParameterizedSurfaceRule */

#ifndef _Included_org_Rescue_rjni_RescueParameterizedSurfaceRule
#define _Included_org_Rescue_rjni_RescueParameterizedSurfaceRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueParameterizedSurfaceRule
 * Method:    Create_RescueParameterizedSurfaceRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueParameterizedSurfaceRule_Create_1RescueParameterizedSurfaceRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueParameterizedSurfaceRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueParameterizedSurfaceRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueParameterizedSurfaceRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueParameterizedSurfaceRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
