/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueStandardPropertyGroupingRule */

#ifndef _Included_org_Rescue_rjni_RescueStandardPropertyGroupingRule
#define _Included_org_Rescue_rjni_RescueStandardPropertyGroupingRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueStandardPropertyGroupingRule
 * Method:    Create_RescueStandardPropertyGroupingRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueStandardPropertyGroupingRule_Create_1RescueStandardPropertyGroupingRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueStandardPropertyGroupingRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueStandardPropertyGroupingRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueStandardPropertyGroupingRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueStandardPropertyGroupingRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
