/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cBagRescueGeobodyPart */

#ifndef _Included_org_Rescue_rjni_cBagRescueGeobodyPart
#define _Included_org_Rescue_rjni_cBagRescueGeobodyPart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cBagRescueGeobodyPart
 * Method:    Create_cBagRescueGeobodyPart0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueGeobodyPart_Create_1cBagRescueGeobodyPart0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cBagRescueGeobodyPart
 * Method:    Delete_cBagRescueGeobodyPart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueGeobodyPart_Delete_1cBagRescueGeobodyPart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueGeobodyPart
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueGeobodyPart_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueGeobodyPart
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cBagRescueGeobodyPart_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueGeobodyPart
 * Method:    NthObject4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueGeobodyPart_NthObject4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueGeobodyPart
 * Method:    Count5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueGeobodyPart_Count5
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
