/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cBagRescueHistory */

#ifndef _Included_org_Rescue_rjni_cBagRescueHistory
#define _Included_org_Rescue_rjni_cBagRescueHistory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cBagRescueHistory
 * Method:    Create_cBagRescueHistory0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueHistory_Create_1cBagRescueHistory0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cBagRescueHistory
 * Method:    Delete_cBagRescueHistory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueHistory_Delete_1cBagRescueHistory
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueHistory
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueHistory_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueHistory
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cBagRescueHistory_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueHistory
 * Method:    NthObject4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueHistory_NthObject4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueHistory
 * Method:    Count5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueHistory_Count5
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
