/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueStandardModelPropertyGroupingRule */

#ifndef _Included_org_Rescue_rjni_RescueStandardModelPropertyGroupingRule
#define _Included_org_Rescue_rjni_RescueStandardModelPropertyGroupingRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueStandardModelPropertyGroupingRule
 * Method:    Create_RescueStandardModelPropertyGroupingRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueStandardModelPropertyGroupingRule_Create_1RescueStandardModelPropertyGroupingRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueStandardModelPropertyGroupingRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueStandardModelPropertyGroupingRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueStandardModelPropertyGroupingRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueStandardModelPropertyGroupingRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
