/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueAndUpVersionRule */

#ifndef _Included_org_Rescue_rjni_RescueAndUpVersionRule
#define _Included_org_Rescue_rjni_RescueAndUpVersionRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueAndUpVersionRule
 * Method:    Create_RescueAndUpVersionRule0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueAndUpVersionRule_Create_1RescueAndUpVersionRule0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_Rescue_rjni_RescueAndUpVersionRule
 * Method:    Create_RescueAndUpVersionRule1
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueAndUpVersionRule_Create_1RescueAndUpVersionRule1
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueAndUpVersionRule
 * Method:    print2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueAndUpVersionRule_print2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueAndUpVersionRule
 * Method:    apply3
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueAndUpVersionRule_apply3
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
