/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescuePreV30ValidatorRule */

#ifndef _Included_org_Rescue_rjni_RescuePreV30ValidatorRule
#define _Included_org_Rescue_rjni_RescuePreV30ValidatorRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescuePreV30ValidatorRule
 * Method:    Create_RescuePreV30ValidatorRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePreV30ValidatorRule_Create_1RescuePreV30ValidatorRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescuePreV30ValidatorRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePreV30ValidatorRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePreV30ValidatorRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescuePreV30ValidatorRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePreV30ValidatorRule
 * Method:    toleranceFactor3
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePreV30ValidatorRule_toleranceFactor3
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     org_Rescue_rjni_RescuePreV30ValidatorRule
 * Method:    toleranceFactor4
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescuePreV30ValidatorRule_toleranceFactor4
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
