/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueSplitNodesRule */

#ifndef _Included_org_Rescue_rjni_RescueSplitNodesRule
#define _Included_org_Rescue_rjni_RescueSplitNodesRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueSplitNodesRule
 * Method:    Create_RescueSplitNodesRule0
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSplitNodesRule_Create_1RescueSplitNodesRule0
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_Rescue_rjni_RescueSplitNodesRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSplitNodesRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSplitNodesRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueSplitNodesRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSplitNodesRule
 * Method:    Equals3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueSplitNodesRule_Equals3
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
