/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescueReservoir */

#ifndef _Included_org_Rescue_rjni_cSetRescueReservoir
#define _Included_org_Rescue_rjni_cSetRescueReservoir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    Create_cSetRescueReservoir0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_Create_1cSetRescueReservoir0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    Delete_cSetRescueReservoir
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_Delete_1cSetRescueReservoir
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    NthObject5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_NthObject5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    ObjectIdentifiedBy6
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_ObjectIdentifiedBy6
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    Count7
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_Count7
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    EmptySelf8
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_EmptySelf8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReservoir
 * Method:    Relink11
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueReservoir_Relink11
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
