/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueVersionRule */

#ifndef _Included_org_Rescue_rjni_RescueVersionRule
#define _Included_org_Rescue_rjni_RescueVersionRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueVersionRule
 * Method:    Delete_RescueVersionRule
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueVersionRule_Delete_1RescueVersionRule
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueVersionRule
 * Method:    print3
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueVersionRule_print3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueVersionRule
 * Method:    apply4
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueVersionRule_apply4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueVersionRule
 * Method:    version5
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueVersionRule_version5
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueVersionRule
 * Method:    Equals6
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueVersionRule_Equals6
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
