/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescuePolyLineNode */

#ifndef _Included_org_Rescue_rjni_RescuePolyLineNode
#define _Included_org_Rescue_rjni_RescuePolyLineNode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescuePolyLineNode_R_TOMBSTONE
#define org_Rescue_rjni_RescuePolyLineNode_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueObject
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueObject 1L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueModel
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueModel 2L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueBlock
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueBlock 3L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueUnit
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueUnit 4L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueHorizon
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueSection
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueSection 6L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueBlockUnit
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueProperty
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueProperty 9L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePropertyGroup
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueWellbore
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueWellboreProperty
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueGrid
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueGrid 14L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueGridAxis
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueArray
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueArray 16L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueTripletArray
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueVertex
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueVertex 19L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueSurface
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueSurface 21L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueDoubletArray
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimVertex
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueEdgeSet
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimEdge
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLine
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNode
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueGeometry
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueSurfaceCell
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueWellboreSampling
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueWellboreSurface
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueWellboreCell
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueReferenceSurface
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueLookup
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueLookup 35L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueLookupItem
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueLookupString
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueLookupTable
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayDouble
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayByte
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayShort
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimLoop
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayFloat
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueMacroVolume
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueBitArray
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueColor
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueColor 48L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueHistory
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueHistory 49L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueHistoryObject
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueArray2dVector
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueArray3dVector
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueColorTable
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueColorTableList
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueGeobody
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueGeobodyPart
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueGeobodySurface
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueIJSurface
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueCellShape
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueEventDescr
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueLogicalOrder
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueFaultIntersection
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueWireframeStub
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineStub
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueWireframe
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueWireframeOwner
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayInt
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueGeometryUnit
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueReservoir
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescuePolyLineNode_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescuePolyLineNode_R_RescueDataContainer
#define org_Rescue_rjni_RescuePolyLineNode_R_RescueDataContainer 82L
#undef org_Rescue_rjni_RescuePolyLineNode_I_SECTION
#define org_Rescue_rjni_RescuePolyLineNode_I_SECTION 0L
#undef org_Rescue_rjni_RescuePolyLineNode_J_SECTION
#define org_Rescue_rjni_RescuePolyLineNode_J_SECTION 1L
#undef org_Rescue_rjni_RescuePolyLineNode_K_SLICE
#define org_Rescue_rjni_RescuePolyLineNode_K_SLICE 2L
/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    Delete_RescuePolyLineNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_Delete_1RescuePolyLineNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    Create_RescuePolyLineNode1
 * Signature: (JDDD)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_Create_1RescuePolyLineNode1
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    Create_RescuePolyLineNode2
 * Signature: (JFFF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_Create_1RescuePolyLineNode2
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    SetXYZValue3
 * Signature: (JDDD)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_SetXYZValue3
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    SetXYZValue4
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_SetXYZValue4
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    X5
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_X5
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    Y6
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_Y6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    Z7
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_Z7
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    SetUVValue8
 * Signature: (JJFF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_SetUVValue8
  (JNIEnv *, jobject, jlong, jlong, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    FaceCount9
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_FaceCount9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    NthFace10
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_NthFace10
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    U11
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_U11
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    V12
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_V12
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    SurfaceOnNode13
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_SurfaceOnNode13
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    SetUVValue14
 * Signature: (JJJFF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_SetUVValue14
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    TSurfCount15
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_TSurfCount15
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    NthTSurf16
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_NthTSurf16
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    U17
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_U17
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    V18
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_V18
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    FaceNdx19
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_FaceNdx19
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    SurfaceOnNode20
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_SurfaceOnNode20
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    SetLayerValue21
 * Signature: (JJIF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_SetLayerValue21
  (JNIEnv *, jobject, jlong, jlong, jint, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    LayerCount22
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_LayerCount22
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    NthLayer23
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_NthLayer23
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    ParamOn24
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_ParamOn24
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescuePolyLineNode
 * Method:    IsOfType25
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescuePolyLineNode_IsOfType25
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
