/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cBagRescueWellboreSurface */

#ifndef _Included_org_Rescue_rjni_cBagRescueWellboreSurface
#define _Included_org_Rescue_rjni_cBagRescueWellboreSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreSurface
 * Method:    Create_cBagRescueWellboreSurface0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueWellboreSurface_Create_1cBagRescueWellboreSurface0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreSurface
 * Method:    Delete_cBagRescueWellboreSurface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueWellboreSurface_Delete_1cBagRescueWellboreSurface
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreSurface
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueWellboreSurface_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreSurface
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cBagRescueWellboreSurface_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreSurface
 * Method:    NthObject4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueWellboreSurface_NthObject4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreSurface
 * Method:    Count5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueWellboreSurface_Count5
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
