/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescueTrimLoopStub */

#ifndef _Included_org_Rescue_rjni_cSetRescueTrimLoopStub
#define _Included_org_Rescue_rjni_cSetRescueTrimLoopStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    Create_cSetRescueTrimLoopStub0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_Create_1cSetRescueTrimLoopStub0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    Delete_cSetRescueTrimLoopStub
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_Delete_1cSetRescueTrimLoopStub
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    NthObject5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_NthObject5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    ObjectNamed6
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_ObjectNamed6
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    ObjectIdentifiedBy7
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_ObjectIdentifiedBy7
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    Count8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_Count8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    EmptySelf9
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_EmptySelf9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueTrimLoopStub
 * Method:    Relink12
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueTrimLoopStub_Relink12
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
