/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueGeometryLGRList */

#ifndef _Included_org_Rescue_rjni_RescueGeometryLGRList
#define _Included_org_Rescue_rjni_RescueGeometryLGRList
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueGeometryLGRList
 * Method:    Create_RescueGeometryLGRList0
 * Signature: (JZJLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometryLGRList_Create_1RescueGeometryLGRList0
  (JNIEnv *, jobject, jlong, jboolean, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueGeometryLGRList
 * Method:    Delete_RescueGeometryLGRList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometryLGRList_Delete_1RescueGeometryLGRList
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometryLGRList
 * Method:    Count1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometryLGRList_Count1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometryLGRList
 * Method:    NthRowGeometry3
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometryLGRList_NthRowGeometry3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometryLGRList
 * Method:    NthRowTimeStepGroup4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometryLGRList_NthRowTimeStepGroup4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometryLGRList
 * Method:    NthRowPropertyGroup5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometryLGRList_NthRowPropertyGroup5
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
