/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueSplitLine */

#ifndef _Included_org_Rescue_rjni_RescueSplitLine
#define _Included_org_Rescue_rjni_RescueSplitLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueSplitLine
 * Method:    Delete_RescueSplitLine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSplitLine_Delete_1RescueSplitLine
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
