/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueFlavourFactory */

#ifndef _Included_org_Rescue_rjni_RescueFlavourFactory
#define _Included_org_Rescue_rjni_RescueFlavourFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueFlavourFactory
 * Method:    create0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueFlavourFactory_create0
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
