/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueBeforeVersionRule */

#ifndef _Included_org_Rescue_rjni_RescueBeforeVersionRule
#define _Included_org_Rescue_rjni_RescueBeforeVersionRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueBeforeVersionRule
 * Method:    Create_RescueBeforeVersionRule0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBeforeVersionRule_Create_1RescueBeforeVersionRule0
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_Rescue_rjni_RescueBeforeVersionRule
 * Method:    Create_RescueBeforeVersionRule1
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBeforeVersionRule_Create_1RescueBeforeVersionRule1
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueBeforeVersionRule
 * Method:    print2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBeforeVersionRule_print2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBeforeVersionRule
 * Method:    apply3
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueBeforeVersionRule_apply3
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
