/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescueReferenceSurface */

#ifndef _Included_org_Rescue_rjni_cSetRescueReferenceSurface
#define _Included_org_Rescue_rjni_cSetRescueReferenceSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    Create_cSetRescueReferenceSurface0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_Create_1cSetRescueReferenceSurface0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    Delete_cSetRescueReferenceSurface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_Delete_1cSetRescueReferenceSurface
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    NthObject5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_NthObject5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    ObjectNamed6
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_ObjectNamed6
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    ObjectIdentifiedBy7
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_ObjectIdentifiedBy7
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    Count8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_Count8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    EmptySelf9
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_EmptySelf9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    Relink12
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_Relink12
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueReferenceSurface
 * Method:    AnyFileTruncated13
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueReferenceSurface_AnyFileTruncated13
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
