/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueZStack */

#ifndef _Included_org_Rescue_rjni_RescueZStack
#define _Included_org_Rescue_rjni_RescueZStack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueZStack
 * Method:    Delete_RescueZStack
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueZStack_Delete_1RescueZStack
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
