/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueBlockAndUnitNumbersRule */

#ifndef _Included_org_Rescue_rjni_RescueBlockAndUnitNumbersRule
#define _Included_org_Rescue_rjni_RescueBlockAndUnitNumbersRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueBlockAndUnitNumbersRule
 * Method:    Create_RescueBlockAndUnitNumbersRule0
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockAndUnitNumbersRule_Create_1RescueBlockAndUnitNumbersRule0
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
