/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface */

#ifndef _Included_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
#define _Included_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    Create_cSetRescueBlockUnitHorizonSurface0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_Create_1cSetRescueBlockUnitHorizonSurface0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    Delete_cSetRescueBlockUnitHorizonSurface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_Delete_1cSetRescueBlockUnitHorizonSurface
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    NthObject5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_NthObject5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    ObjectNamed6
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_ObjectNamed6
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    ObjectIdentifiedBy7
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_ObjectIdentifiedBy7
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    Count8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_Count8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    EmptySelf9
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_EmptySelf9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    Relink12
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_Relink12
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    Dispose13
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_Dispose13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface
 * Method:    AnyFileTruncated14
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueBlockUnitHorizonSurface_AnyFileTruncated14
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
