/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescueGeobodySurface */

#ifndef _Included_org_Rescue_rjni_cSetRescueGeobodySurface
#define _Included_org_Rescue_rjni_cSetRescueGeobodySurface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    Create_cSetRescueGeobodySurface0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_Create_1cSetRescueGeobodySurface0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    Delete_cSetRescueGeobodySurface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_Delete_1cSetRescueGeobodySurface
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    NthObject5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_NthObject5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    ObjectNamed6
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_ObjectNamed6
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    ObjectIdentifiedBy7
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_ObjectIdentifiedBy7
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    Count8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_Count8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    EmptySelf9
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_EmptySelf9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueGeobodySurface
 * Method:    Relink12
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueGeobodySurface_Relink12
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
