/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueSurface */

#ifndef _Included_org_Rescue_rjni_RescueSurface
#define _Included_org_Rescue_rjni_RescueSurface
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueSurface_R_TOMBSTONE
#define org_Rescue_rjni_RescueSurface_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescueSurface_R_RescueObject
#define org_Rescue_rjni_RescueSurface_R_RescueObject 1L
#undef org_Rescue_rjni_RescueSurface_R_RescueModel
#define org_Rescue_rjni_RescueSurface_R_RescueModel 2L
#undef org_Rescue_rjni_RescueSurface_R_RescueBlock
#define org_Rescue_rjni_RescueSurface_R_RescueBlock 3L
#undef org_Rescue_rjni_RescueSurface_R_RescueUnit
#define org_Rescue_rjni_RescueSurface_R_RescueUnit 4L
#undef org_Rescue_rjni_RescueSurface_R_RescueHorizon
#define org_Rescue_rjni_RescueSurface_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescueSurface_R_RescueSection
#define org_Rescue_rjni_RescueSurface_R_RescueSection 6L
#undef org_Rescue_rjni_RescueSurface_R_RescueBlockUnit
#define org_Rescue_rjni_RescueSurface_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescueSurface_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescueSurface_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescueSurface_R_RescueProperty
#define org_Rescue_rjni_RescueSurface_R_RescueProperty 9L
#undef org_Rescue_rjni_RescueSurface_R_RescuePropertyGroup
#define org_Rescue_rjni_RescueSurface_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescueSurface_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescueSurface_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescueSurface_R_RescueWellbore
#define org_Rescue_rjni_RescueSurface_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescueSurface_R_RescueWellboreProperty
#define org_Rescue_rjni_RescueSurface_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescueSurface_R_RescueGrid
#define org_Rescue_rjni_RescueSurface_R_RescueGrid 14L
#undef org_Rescue_rjni_RescueSurface_R_RescueGridAxis
#define org_Rescue_rjni_RescueSurface_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescueSurface_R_RescueArray
#define org_Rescue_rjni_RescueSurface_R_RescueArray 16L
#undef org_Rescue_rjni_RescueSurface_R_RescueTripletArray
#define org_Rescue_rjni_RescueSurface_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescueSurface_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescueSurface_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescueSurface_R_RescueVertex
#define org_Rescue_rjni_RescueSurface_R_RescueVertex 19L
#undef org_Rescue_rjni_RescueSurface_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescueSurface_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescueSurface_R_RescueSurface
#define org_Rescue_rjni_RescueSurface_R_RescueSurface 21L
#undef org_Rescue_rjni_RescueSurface_R_RescueDoubletArray
#define org_Rescue_rjni_RescueSurface_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescueSurface_R_RescueTrimVertex
#define org_Rescue_rjni_RescueSurface_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescueSurface_R_RescueEdgeSet
#define org_Rescue_rjni_RescueSurface_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescueSurface_R_RescueTrimEdge
#define org_Rescue_rjni_RescueSurface_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescueSurface_R_RescuePolyLine
#define org_Rescue_rjni_RescueSurface_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescueSurface_R_RescuePolyLineNode
#define org_Rescue_rjni_RescueSurface_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescueSurface_R_RescueGeometry
#define org_Rescue_rjni_RescueSurface_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescueSurface_R_RescueSurfaceCell
#define org_Rescue_rjni_RescueSurface_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescueSurface_R_RescueWellboreSampling
#define org_Rescue_rjni_RescueSurface_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescueSurface_R_RescueWellboreSurface
#define org_Rescue_rjni_RescueSurface_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescueSurface_R_RescueWellboreCell
#define org_Rescue_rjni_RescueSurface_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescueSurface_R_RescueReferenceSurface
#define org_Rescue_rjni_RescueSurface_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescueSurface_R_RescueLookup
#define org_Rescue_rjni_RescueSurface_R_RescueLookup 35L
#undef org_Rescue_rjni_RescueSurface_R_RescueLookupItem
#define org_Rescue_rjni_RescueSurface_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescueSurface_R_RescueLookupString
#define org_Rescue_rjni_RescueSurface_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescueSurface_R_RescueLookupTable
#define org_Rescue_rjni_RescueSurface_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescueSurface_R_RescueArrayDouble
#define org_Rescue_rjni_RescueSurface_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescueSurface_R_RescueArrayByte
#define org_Rescue_rjni_RescueSurface_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescueSurface_R_RescueArrayShort
#define org_Rescue_rjni_RescueSurface_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescueSurface_R_RescueTrimLoop
#define org_Rescue_rjni_RescueSurface_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescueSurface_R_RescueArrayFloat
#define org_Rescue_rjni_RescueSurface_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescueSurface_R_RescueMacroVolume
#define org_Rescue_rjni_RescueSurface_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescueSurface_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescueSurface_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescueSurface_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescueSurface_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescueSurface_R_RescueBitArray
#define org_Rescue_rjni_RescueSurface_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescueSurface_R_RescueColor
#define org_Rescue_rjni_RescueSurface_R_RescueColor 48L
#undef org_Rescue_rjni_RescueSurface_R_RescueHistory
#define org_Rescue_rjni_RescueSurface_R_RescueHistory 49L
#undef org_Rescue_rjni_RescueSurface_R_RescueHistoryObject
#define org_Rescue_rjni_RescueSurface_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescueSurface_R_RescueArray2dVector
#define org_Rescue_rjni_RescueSurface_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescueSurface_R_RescueArray3dVector
#define org_Rescue_rjni_RescueSurface_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescueSurface_R_RescueColorTable
#define org_Rescue_rjni_RescueSurface_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescueSurface_R_RescueColorTableList
#define org_Rescue_rjni_RescueSurface_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescueSurface_R_RescueGeobody
#define org_Rescue_rjni_RescueSurface_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescueSurface_R_RescueGeobodyPart
#define org_Rescue_rjni_RescueSurface_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescueSurface_R_RescueGeobodySurface
#define org_Rescue_rjni_RescueSurface_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescueSurface_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescueSurface_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescueSurface_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescueSurface_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescueSurface_R_RescueIJSurface
#define org_Rescue_rjni_RescueSurface_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescueSurface_R_RescueCellShape
#define org_Rescue_rjni_RescueSurface_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescueSurface_R_RescueEventDescr
#define org_Rescue_rjni_RescueSurface_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescueSurface_R_RescueLogicalOrder
#define org_Rescue_rjni_RescueSurface_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescueSurface_R_RescueFaultIntersection
#define org_Rescue_rjni_RescueSurface_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescueSurface_R_RescueWireframeStub
#define org_Rescue_rjni_RescueSurface_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescueSurface_R_RescuePolyLineStub
#define org_Rescue_rjni_RescueSurface_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescueSurface_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescueSurface_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescueSurface_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescueSurface_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescueSurface_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescueSurface_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescueSurface_R_RescueWireframe
#define org_Rescue_rjni_RescueSurface_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescueSurface_R_RescueWireframeOwner
#define org_Rescue_rjni_RescueSurface_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescueSurface_R_RescueArrayInt
#define org_Rescue_rjni_RescueSurface_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescueSurface_R_RescueGeometryUnit
#define org_Rescue_rjni_RescueSurface_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescueSurface_R_RescueReservoir
#define org_Rescue_rjni_RescueSurface_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescueSurface_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescueSurface_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescueSurface_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescueSurface_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescueSurface_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescueSurface_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescueSurface_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescueSurface_R_RescueDataContainer
#define org_Rescue_rjni_RescueSurface_R_RescueDataContainer 82L
#undef org_Rescue_rjni_RescueSurface_AUXILLIARY
#define org_Rescue_rjni_RescueSurface_AUXILLIARY 0L
#undef org_Rescue_rjni_RescueSurface_FAULT
#define org_Rescue_rjni_RescueSurface_FAULT 1L
#undef org_Rescue_rjni_RescueSurface_UNCONFORMITY
#define org_Rescue_rjni_RescueSurface_UNCONFORMITY 2L
#undef org_Rescue_rjni_RescueSurface_LEASE_BOUNDARY
#define org_Rescue_rjni_RescueSurface_LEASE_BOUNDARY 3L
#undef org_Rescue_rjni_RescueSurface_HORIZON
#define org_Rescue_rjni_RescueSurface_HORIZON 4L
#undef org_Rescue_rjni_RescueSurface_OIL_CONTACT
#define org_Rescue_rjni_RescueSurface_OIL_CONTACT 5L
#undef org_Rescue_rjni_RescueSurface_GAS_CONTACT
#define org_Rescue_rjni_RescueSurface_GAS_CONTACT 6L
#undef org_Rescue_rjni_RescueSurface_WATER_CONTACT
#define org_Rescue_rjni_RescueSurface_WATER_CONTACT 7L
#undef org_Rescue_rjni_RescueSurface_SALT_DOME
#define org_Rescue_rjni_RescueSurface_SALT_DOME 8L
/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    Create_RescueSurface0
 * Signature: (JIJFFJJJFFJJFI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_Create_1RescueSurface0
  (JNIEnv *, jobject, jlong, jint, jlong, jfloat, jfloat, jlong, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat, jint);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    Create_RescueSurface1
 * Signature: (JIJFFJJJFFJJF[FI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_Create_1RescueSurface1
  (JNIEnv *, jobject, jlong, jint, jlong, jfloat, jfloat, jlong, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloatArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    Create_RescueSurface2
 * Signature: (JIJJJJFI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_Create_1RescueSurface2
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jlong, jlong, jfloat, jint);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    Create_RescueSurface3
 * Signature: (JIJJJJF[FI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_Create_1RescueSurface3
  (JNIEnv *, jobject, jlong, jint, jlong, jlong, jlong, jlong, jfloat, jfloatArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    EdgesObj4
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_EdgesObj4
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    Edges5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_Edges5
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    AnyFileTruncated6
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueSurface_AnyFileTruncated6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    IsOfType7
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueSurface_IsOfType7
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    Delete_RescueSurface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSurface_Delete_1RescueSurface
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    Type9
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueSurface_Type9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    SetColor11
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSurface_SetColor11
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    Color12
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_Color12
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    PropertyCount13
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_PropertyCount13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    NthRescueProperty14
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_NthRescueProperty14
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    PropertyIdentifiedBy15
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_PropertyIdentifiedBy15
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    PropertyNamed16
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_PropertyNamed16
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    DropRescueProperty17
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueSurface_DropRescueProperty17
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    IJSurfaceCount18
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_IJSurfaceCount18
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    NthIJSurface19
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_NthIJSurface19
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    SurfaceIJIdentifiedBy20
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_SurfaceIJIdentifiedBy20
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    SurfaceTriangulatedIdentifiedBy21
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_SurfaceTriangulatedIdentifiedBy21
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    DropIJSurface22
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueSurface_DropIJSurface22
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    ParentModel23
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_ParentModel23
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    CountOfPropertyGroup24
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_CountOfPropertyGroup24
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    AddPropertyGroup25
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSurface_AddPropertyGroup25
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    DeletePropertyGroup26
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueSurface_DeletePropertyGroup26
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    NthPropertyGroup27
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_NthPropertyGroup27
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    CreateTriangulatedSurface28
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_CreateTriangulatedSurface28
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    CreateTriangulatedSurface29
 * Signature: (JJ[[FJ[[J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_CreateTriangulatedSurface29
  (JNIEnv *, jobject, jlong, jlong, jobjectArray, jlong, jobjectArray);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    CreateTriangulatedSurface29i
 * Signature: (JI[[FI[[I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_CreateTriangulatedSurface29i
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint, jobjectArray);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    CreateTriangulatedSurface30
 * Signature: (JJ[FJ[J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_CreateTriangulatedSurface30
  (JNIEnv *, jobject, jlong, jlong, jfloatArray, jlong, jlongArray);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    CreateTriangulatedSurface30i
 * Signature: (JI[FI[I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_CreateTriangulatedSurface30i
  (JNIEnv *, jobject, jlong, jint, jfloatArray, jint, jintArray);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    TriangulatedSurface31
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_TriangulatedSurface31
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    DataContainers32
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_DataContainers32
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSurface
 * Method:    DemandDataContainers33
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSurface_DemandDataContainers33
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
