/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescuePassRule */

#ifndef _Included_org_Rescue_rjni_RescuePassRule
#define _Included_org_Rescue_rjni_RescuePassRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescuePassRule
 * Method:    Create_RescuePassRule0
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePassRule_Create_1RescuePassRule0
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_Rescue_rjni_RescuePassRule
 * Method:    Create_RescuePassRule1
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePassRule_Create_1RescuePassRule1
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescuePassRule
 * Method:    print2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePassRule_print2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePassRule
 * Method:    apply3
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescuePassRule_apply3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePassRule
 * Method:    Equals4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescuePassRule_Equals4
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
