/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueArrayFragmentInt */

#ifndef _Included_org_Rescue_rjni_RescueArrayFragmentInt
#define _Included_org_Rescue_rjni_RescueArrayFragmentInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueArrayFragmentInt
 * Method:    Delete_RescueArrayFragmentInt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayFragmentInt_Delete_1RescueArrayFragmentInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragmentInt
 * Method:    Value1
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_org_Rescue_rjni_RescueArrayFragmentInt_Value1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragmentInt
 * Method:    ValueLength2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragmentInt_ValueLength2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragmentInt
 * Method:    SetValue3
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayFragmentInt_SetValue3
  (JNIEnv *, jobject, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
