/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueRefIdRule */

#ifndef _Included_org_Rescue_rjni_RescueRefIdRule
#define _Included_org_Rescue_rjni_RescueRefIdRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueRefIdRule
 * Method:    Create_RescueRefIdRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueRefIdRule_Create_1RescueRefIdRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueRefIdRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueRefIdRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueRefIdRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueRefIdRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
