/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cBagRescueSurfaceToGrid */

#ifndef _Included_org_Rescue_rjni_cBagRescueSurfaceToGrid
#define _Included_org_Rescue_rjni_cBagRescueSurfaceToGrid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cBagRescueSurfaceToGrid
 * Method:    Create_cBagRescueSurfaceToGrid0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueSurfaceToGrid_Create_1cBagRescueSurfaceToGrid0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cBagRescueSurfaceToGrid
 * Method:    Delete_cBagRescueSurfaceToGrid
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueSurfaceToGrid_Delete_1cBagRescueSurfaceToGrid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueSurfaceToGrid
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueSurfaceToGrid_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueSurfaceToGrid
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cBagRescueSurfaceToGrid_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueSurfaceToGrid
 * Method:    NthObject4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueSurfaceToGrid_NthObject4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueSurfaceToGrid
 * Method:    Count5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueSurfaceToGrid_Count5
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
