/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueLGRIDRule */

#ifndef _Included_org_Rescue_rjni_RescueLGRIDRule
#define _Included_org_Rescue_rjni_RescueLGRIDRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueLGRIDRule
 * Method:    Create_RescueLGRIDRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueLGRIDRule_Create_1RescueLGRIDRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueLGRIDRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueLGRIDRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueLGRIDRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueLGRIDRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
