/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueGoodVolumeRule */

#ifndef _Included_org_Rescue_rjni_RescueGoodVolumeRule
#define _Included_org_Rescue_rjni_RescueGoodVolumeRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueGoodVolumeRule
 * Method:    Create_RescueGoodVolumeRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGoodVolumeRule_Create_1RescueGoodVolumeRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueGoodVolumeRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGoodVolumeRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGoodVolumeRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGoodVolumeRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
