/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cBagInt */

#ifndef _Included_org_Rescue_rjni_cBagInt
#define _Included_org_Rescue_rjni_cBagInt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cBagInt
 * Method:    Create_cBagInt0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagInt_Create_1cBagInt0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cBagInt
 * Method:    Delete_cBagInt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagInt_Delete_1cBagInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cBagInt
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagInt_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagInt
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cBagInt_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagInt
 * Method:    NthObject4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagInt_NthObject4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagInt
 * Method:    Count5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagInt_Count5
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cBagInt
 * Method:    Contains6
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cBagInt_Contains6
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
