/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueIdTreeNode */

#ifndef _Included_org_Rescue_rjni_RescueIdTreeNode
#define _Included_org_Rescue_rjni_RescueIdTreeNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueIdTreeNode
 * Method:    Delete_RescueIdTreeNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueIdTreeNode_Delete_1RescueIdTreeNode
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
