/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cNameValuePair */

#ifndef _Included_org_Rescue_rjni_cNameValuePair
#define _Included_org_Rescue_rjni_cNameValuePair
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cNameValuePair
 * Method:    NthName0
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_cNameValuePair_NthName0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cNameValuePair
 * Method:    NthValue1
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_cNameValuePair_NthValue1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cNameValuePair
 * Method:    Count2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cNameValuePair_Count2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cNameValuePair
 * Method:    Contains3
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cNameValuePair_Contains3
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cNameValuePair
 * Method:    SetNameValuePair4
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cNameValuePair_SetNameValuePair4
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     org_Rescue_rjni_cNameValuePair
 * Method:    GetNameValuePair5
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_cNameValuePair_GetNameValuePair5
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
