/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_classifier */

#ifndef _Included_org_Rescue_rjni_classifier
#define _Included_org_Rescue_rjni_classifier
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
