/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueNoGlobalsRule */

#ifndef _Included_org_Rescue_rjni_RescueNoGlobalsRule
#define _Included_org_Rescue_rjni_RescueNoGlobalsRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueNoGlobalsRule
 * Method:    Create_RescueNoGlobalsRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueNoGlobalsRule_Create_1RescueNoGlobalsRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueNoGlobalsRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueNoGlobalsRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueNoGlobalsRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueNoGlobalsRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
