/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cBagRescueWellboreCell */

#ifndef _Included_org_Rescue_rjni_cBagRescueWellboreCell
#define _Included_org_Rescue_rjni_cBagRescueWellboreCell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreCell
 * Method:    Create_cBagRescueWellboreCell0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueWellboreCell_Create_1cBagRescueWellboreCell0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreCell
 * Method:    Delete_cBagRescueWellboreCell
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueWellboreCell_Delete_1cBagRescueWellboreCell
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreCell
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cBagRescueWellboreCell_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreCell
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cBagRescueWellboreCell_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreCell
 * Method:    NthObject4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueWellboreCell_NthObject4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cBagRescueWellboreCell
 * Method:    Count5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cBagRescueWellboreCell_Count5
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
