/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescueLookup */

#ifndef _Included_org_Rescue_rjni_cSetRescueLookup
#define _Included_org_Rescue_rjni_cSetRescueLookup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    Create_cSetRescueLookup0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueLookup_Create_1cSetRescueLookup0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    Delete_cSetRescueLookup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueLookup_Delete_1cSetRescueLookup
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueLookup_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueLookup_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueLookup_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    NthObject5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueLookup_NthObject5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    ObjectNamed6
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueLookup_ObjectNamed6
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    ObjectIdentifiedBy7
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueLookup_ObjectIdentifiedBy7
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    Count8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueLookup_Count8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    EmptySelf9
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueLookup_EmptySelf9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueLookup
 * Method:    Relink12
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueLookup_Relink12
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
