/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueSOctTreeNode */

#ifndef _Included_org_Rescue_rjni_RescueSOctTreeNode
#define _Included_org_Rescue_rjni_RescueSOctTreeNode
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueSOctTreeNode_BOTTOM_LEFT_FRONT
#define org_Rescue_rjni_RescueSOctTreeNode_BOTTOM_LEFT_FRONT 0L
#undef org_Rescue_rjni_RescueSOctTreeNode_BOTTOM_RIGHT_FRONT
#define org_Rescue_rjni_RescueSOctTreeNode_BOTTOM_RIGHT_FRONT 1L
#undef org_Rescue_rjni_RescueSOctTreeNode_BOTTOM_RIGHT_REAR
#define org_Rescue_rjni_RescueSOctTreeNode_BOTTOM_RIGHT_REAR 2L
#undef org_Rescue_rjni_RescueSOctTreeNode_BOTTOM_LEFT_REAR
#define org_Rescue_rjni_RescueSOctTreeNode_BOTTOM_LEFT_REAR 3L
#undef org_Rescue_rjni_RescueSOctTreeNode_TOP_LEFT_FRONT
#define org_Rescue_rjni_RescueSOctTreeNode_TOP_LEFT_FRONT 4L
#undef org_Rescue_rjni_RescueSOctTreeNode_TOP_RIGHT_FRONT
#define org_Rescue_rjni_RescueSOctTreeNode_TOP_RIGHT_FRONT 5L
#undef org_Rescue_rjni_RescueSOctTreeNode_TOP_RIGHT_REAR
#define org_Rescue_rjni_RescueSOctTreeNode_TOP_RIGHT_REAR 6L
#undef org_Rescue_rjni_RescueSOctTreeNode_TOP_LEFT_REAR
#define org_Rescue_rjni_RescueSOctTreeNode_TOP_LEFT_REAR 7L
/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    Create_RescueSOctTreeNode0
 * Signature: (JFFFFFFJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_Create_1RescueSOctTreeNode0
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    Delete_RescueSOctTreeNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_Delete_1RescueSOctTreeNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    VertexCount2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_VertexCount2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    NthVertex3
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_NthVertex3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    Leaf4
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_Leaf4
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    TerminalNode5
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_TerminalNode5
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    MinX6
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_MinX6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    MaxX7
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_MaxX7
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    MinY8
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_MinY8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    MaxY9
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_MaxY9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    MinZ10
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_MinZ10
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSOctTreeNode
 * Method:    MaxZ11
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSOctTreeNode_MaxZ11
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
