/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueBlockNameRule */

#ifndef _Included_org_Rescue_rjni_RescueBlockNameRule
#define _Included_org_Rescue_rjni_RescueBlockNameRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueBlockNameRule
 * Method:    Create_RescueBlockNameRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockNameRule_Create_1RescueBlockNameRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueBlockNameRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockNameRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockNameRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueBlockNameRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
