/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueUnitNameRule */

#ifndef _Included_org_Rescue_rjni_RescueUnitNameRule
#define _Included_org_Rescue_rjni_RescueUnitNameRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueUnitNameRule
 * Method:    Create_RescueUnitNameRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueUnitNameRule_Create_1RescueUnitNameRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueUnitNameRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueUnitNameRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueUnitNameRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueUnitNameRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
