/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueBUHRule */

#ifndef _Included_org_Rescue_rjni_RescueBUHRule
#define _Included_org_Rescue_rjni_RescueBUHRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueBUHRule
 * Method:    Create_RescueBUHRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBUHRule_Create_1RescueBUHRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueBUHRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBUHRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBUHRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueBUHRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
