/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueLayerToUnitRule */

#ifndef _Included_org_Rescue_rjni_RescueLayerToUnitRule
#define _Included_org_Rescue_rjni_RescueLayerToUnitRule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueLayerToUnitRule
 * Method:    Create_RescueLayerToUnitRule0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueLayerToUnitRule_Create_1RescueLayerToUnitRule0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueLayerToUnitRule
 * Method:    print1
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueLayerToUnitRule_print1
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueLayerToUnitRule
 * Method:    apply2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueLayerToUnitRule_apply2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
