/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueArrayFragment3dVector */

#ifndef _Included_org_Rescue_rjni_RescueArrayFragment3dVector
#define _Included_org_Rescue_rjni_RescueArrayFragment3dVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueArrayFragment3dVector
 * Method:    Delete_RescueArrayFragment3dVector
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayFragment3dVector_Delete_1RescueArrayFragment3dVector
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment3dVector
 * Method:    Value1
 * Signature: (J)[Lorg/Rescue/rjni/Rescue3dVector;
 */
JNIEXPORT jobjectArray JNICALL Java_org_Rescue_rjni_RescueArrayFragment3dVector_Value1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment3dVector
 * Method:    ValueLength2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragment3dVector_ValueLength2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment3dVector
 * Method:    SetValue3
 * Signature: (J[Lorg/Rescue/rjni/Rescue3dVector;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayFragment3dVector_SetValue3
  (JNIEnv *, jobject, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
