/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueGeometry */

#ifndef _Included_org_Rescue_rjni_RescueGeometry
#define _Included_org_Rescue_rjni_RescueGeometry
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueGeometry_R_TOMBSTONE
#define org_Rescue_rjni_RescueGeometry_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescueGeometry_R_RescueObject
#define org_Rescue_rjni_RescueGeometry_R_RescueObject 1L
#undef org_Rescue_rjni_RescueGeometry_R_RescueModel
#define org_Rescue_rjni_RescueGeometry_R_RescueModel 2L
#undef org_Rescue_rjni_RescueGeometry_R_RescueBlock
#define org_Rescue_rjni_RescueGeometry_R_RescueBlock 3L
#undef org_Rescue_rjni_RescueGeometry_R_RescueUnit
#define org_Rescue_rjni_RescueGeometry_R_RescueUnit 4L
#undef org_Rescue_rjni_RescueGeometry_R_RescueHorizon
#define org_Rescue_rjni_RescueGeometry_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescueGeometry_R_RescueSection
#define org_Rescue_rjni_RescueGeometry_R_RescueSection 6L
#undef org_Rescue_rjni_RescueGeometry_R_RescueBlockUnit
#define org_Rescue_rjni_RescueGeometry_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescueGeometry_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescueGeometry_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescueGeometry_R_RescueProperty
#define org_Rescue_rjni_RescueGeometry_R_RescueProperty 9L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePropertyGroup
#define org_Rescue_rjni_RescueGeometry_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescueGeometry_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescueGeometry_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescueGeometry_R_RescueWellbore
#define org_Rescue_rjni_RescueGeometry_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescueGeometry_R_RescueWellboreProperty
#define org_Rescue_rjni_RescueGeometry_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescueGeometry_R_RescueGrid
#define org_Rescue_rjni_RescueGeometry_R_RescueGrid 14L
#undef org_Rescue_rjni_RescueGeometry_R_RescueGridAxis
#define org_Rescue_rjni_RescueGeometry_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescueGeometry_R_RescueArray
#define org_Rescue_rjni_RescueGeometry_R_RescueArray 16L
#undef org_Rescue_rjni_RescueGeometry_R_RescueTripletArray
#define org_Rescue_rjni_RescueGeometry_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescueGeometry_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescueGeometry_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescueGeometry_R_RescueVertex
#define org_Rescue_rjni_RescueGeometry_R_RescueVertex 19L
#undef org_Rescue_rjni_RescueGeometry_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescueGeometry_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescueGeometry_R_RescueSurface
#define org_Rescue_rjni_RescueGeometry_R_RescueSurface 21L
#undef org_Rescue_rjni_RescueGeometry_R_RescueDoubletArray
#define org_Rescue_rjni_RescueGeometry_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescueGeometry_R_RescueTrimVertex
#define org_Rescue_rjni_RescueGeometry_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescueGeometry_R_RescueEdgeSet
#define org_Rescue_rjni_RescueGeometry_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescueGeometry_R_RescueTrimEdge
#define org_Rescue_rjni_RescueGeometry_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePolyLine
#define org_Rescue_rjni_RescueGeometry_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNode
#define org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescueGeometry_R_RescueGeometry
#define org_Rescue_rjni_RescueGeometry_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescueGeometry_R_RescueSurfaceCell
#define org_Rescue_rjni_RescueGeometry_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescueGeometry_R_RescueWellboreSampling
#define org_Rescue_rjni_RescueGeometry_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescueGeometry_R_RescueWellboreSurface
#define org_Rescue_rjni_RescueGeometry_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescueGeometry_R_RescueWellboreCell
#define org_Rescue_rjni_RescueGeometry_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescueGeometry_R_RescueReferenceSurface
#define org_Rescue_rjni_RescueGeometry_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescueGeometry_R_RescueLookup
#define org_Rescue_rjni_RescueGeometry_R_RescueLookup 35L
#undef org_Rescue_rjni_RescueGeometry_R_RescueLookupItem
#define org_Rescue_rjni_RescueGeometry_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescueGeometry_R_RescueLookupString
#define org_Rescue_rjni_RescueGeometry_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescueGeometry_R_RescueLookupTable
#define org_Rescue_rjni_RescueGeometry_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescueGeometry_R_RescueArrayDouble
#define org_Rescue_rjni_RescueGeometry_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescueGeometry_R_RescueArrayByte
#define org_Rescue_rjni_RescueGeometry_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescueGeometry_R_RescueArrayShort
#define org_Rescue_rjni_RescueGeometry_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescueGeometry_R_RescueTrimLoop
#define org_Rescue_rjni_RescueGeometry_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescueGeometry_R_RescueArrayFloat
#define org_Rescue_rjni_RescueGeometry_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescueGeometry_R_RescueMacroVolume
#define org_Rescue_rjni_RescueGeometry_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescueGeometry_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescueGeometry_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescueGeometry_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescueGeometry_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescueGeometry_R_RescueBitArray
#define org_Rescue_rjni_RescueGeometry_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescueGeometry_R_RescueColor
#define org_Rescue_rjni_RescueGeometry_R_RescueColor 48L
#undef org_Rescue_rjni_RescueGeometry_R_RescueHistory
#define org_Rescue_rjni_RescueGeometry_R_RescueHistory 49L
#undef org_Rescue_rjni_RescueGeometry_R_RescueHistoryObject
#define org_Rescue_rjni_RescueGeometry_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescueGeometry_R_RescueArray2dVector
#define org_Rescue_rjni_RescueGeometry_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescueGeometry_R_RescueArray3dVector
#define org_Rescue_rjni_RescueGeometry_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescueGeometry_R_RescueColorTable
#define org_Rescue_rjni_RescueGeometry_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescueGeometry_R_RescueColorTableList
#define org_Rescue_rjni_RescueGeometry_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescueGeometry_R_RescueGeobody
#define org_Rescue_rjni_RescueGeometry_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescueGeometry_R_RescueGeobodyPart
#define org_Rescue_rjni_RescueGeometry_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescueGeometry_R_RescueGeobodySurface
#define org_Rescue_rjni_RescueGeometry_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescueGeometry_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescueGeometry_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescueGeometry_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescueGeometry_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescueGeometry_R_RescueIJSurface
#define org_Rescue_rjni_RescueGeometry_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescueGeometry_R_RescueCellShape
#define org_Rescue_rjni_RescueGeometry_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescueGeometry_R_RescueEventDescr
#define org_Rescue_rjni_RescueGeometry_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescueGeometry_R_RescueLogicalOrder
#define org_Rescue_rjni_RescueGeometry_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescueGeometry_R_RescueFaultIntersection
#define org_Rescue_rjni_RescueGeometry_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescueGeometry_R_RescueWireframeStub
#define org_Rescue_rjni_RescueGeometry_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePolyLineStub
#define org_Rescue_rjni_RescueGeometry_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescueGeometry_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescueGeometry_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescueGeometry_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescueGeometry_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescueGeometry_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescueGeometry_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescueGeometry_R_RescueWireframe
#define org_Rescue_rjni_RescueGeometry_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescueGeometry_R_RescueWireframeOwner
#define org_Rescue_rjni_RescueGeometry_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescueGeometry_R_RescueArrayInt
#define org_Rescue_rjni_RescueGeometry_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescueGeometry_R_RescueGeometryUnit
#define org_Rescue_rjni_RescueGeometry_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescueGeometry_R_RescueReservoir
#define org_Rescue_rjni_RescueGeometry_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescueGeometry_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescueGeometry_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescueGeometry_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescueGeometry_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescueGeometry_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescueGeometry_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescueGeometry_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescueGeometry_R_RescueDataContainer
#define org_Rescue_rjni_RescueGeometry_R_RescueDataContainer 82L
#undef org_Rescue_rjni_RescueGeometry_R_EQUAL_AXIS
#define org_Rescue_rjni_RescueGeometry_R_EQUAL_AXIS 0L
#undef org_Rescue_rjni_RescueGeometry_R_UNEQUAL_AXIS
#define org_Rescue_rjni_RescueGeometry_R_UNEQUAL_AXIS 1L
#undef org_Rescue_rjni_RescueGeometry_R_COORDINATE_LINE
#define org_Rescue_rjni_RescueGeometry_R_COORDINATE_LINE 2L
#undef org_Rescue_rjni_RescueGeometry_R_COORDINATE_POLYLINE
#define org_Rescue_rjni_RescueGeometry_R_COORDINATE_POLYLINE 3L
#undef org_Rescue_rjni_RescueGeometry_R_SPLIT_LINE
#define org_Rescue_rjni_RescueGeometry_R_SPLIT_LINE 4L
#undef org_Rescue_rjni_RescueGeometry_R_SPLINE_LINE
#define org_Rescue_rjni_RescueGeometry_R_SPLINE_LINE 5L
#undef org_Rescue_rjni_RescueGeometry_R_ONLAP
#define org_Rescue_rjni_RescueGeometry_R_ONLAP 0L
#undef org_Rescue_rjni_RescueGeometry_R_OFFLAP
#define org_Rescue_rjni_RescueGeometry_R_OFFLAP 1L
#undef org_Rescue_rjni_RescueGeometry_R_XY_ORTHOGONAL
#define org_Rescue_rjni_RescueGeometry_R_XY_ORTHOGONAL 0L
#undef org_Rescue_rjni_RescueGeometry_R_SQUASHED_ORTHOGONAL
#define org_Rescue_rjni_RescueGeometry_R_SQUASHED_ORTHOGONAL 1L
#undef org_Rescue_rjni_RescueGeometry_R_CONFORMABLE
#define org_Rescue_rjni_RescueGeometry_R_CONFORMABLE 2L
#undef org_Rescue_rjni_RescueGeometry_R_ACTIVE
#define org_Rescue_rjni_RescueGeometry_R_ACTIVE 0L
#undef org_Rescue_rjni_RescueGeometry_R_INACTIVE
#define org_Rescue_rjni_RescueGeometry_R_INACTIVE 1L
#undef org_Rescue_rjni_RescueGeometry_R_TRUNCATED
#define org_Rescue_rjni_RescueGeometry_R_TRUNCATED 2L
#undef org_Rescue_rjni_RescueGeometry_R_INACTIVATED_BY_PILLAR
#define org_Rescue_rjni_RescueGeometry_R_INACTIVATED_BY_PILLAR 3L
#undef org_Rescue_rjni_RescueGeometry_R_NOT_LGR
#define org_Rescue_rjni_RescueGeometry_R_NOT_LGR 0L
#undef org_Rescue_rjni_RescueGeometry_R_RULE_BASED
#define org_Rescue_rjni_RescueGeometry_R_RULE_BASED 1L
#undef org_Rescue_rjni_RescueGeometry_R_WEIGHT_BASED
#define org_Rescue_rjni_RescueGeometry_R_WEIGHT_BASED 2L
#undef org_Rescue_rjni_RescueGeometry_R_UNCONSTRAINED
#define org_Rescue_rjni_RescueGeometry_R_UNCONSTRAINED 3L
#undef org_Rescue_rjni_RescueGeometry_R_RULE_BASED_NOSPAN
#define org_Rescue_rjni_RescueGeometry_R_RULE_BASED_NOSPAN 4L
#undef org_Rescue_rjni_RescueGeometry_R_WEIGHT_BASED_NOSPAN
#define org_Rescue_rjni_RescueGeometry_R_WEIGHT_BASED_NOSPAN 5L
#undef org_Rescue_rjni_RescueGeometry_R_STRUCTURED_CPG
#define org_Rescue_rjni_RescueGeometry_R_STRUCTURED_CPG 0L
#undef org_Rescue_rjni_RescueGeometry_R_STRUCTURED_RADIAL
#define org_Rescue_rjni_RescueGeometry_R_STRUCTURED_RADIAL 1L
#undef org_Rescue_rjni_RescueGeometry_R_UNSTRUCTURED_TETRAHEDRAL
#define org_Rescue_rjni_RescueGeometry_R_UNSTRUCTURED_TETRAHEDRAL 2L
#undef org_Rescue_rjni_RescueGeometry_R_UNSTRUCTURED_2D_POLYHEDRAL
#define org_Rescue_rjni_RescueGeometry_R_UNSTRUCTURED_2D_POLYHEDRAL 3L
#undef org_Rescue_rjni_RescueGeometry_R_UNSTRUCTURED_3D_POLYHEDRAL
#define org_Rescue_rjni_RescueGeometry_R_UNSTRUCTURED_3D_POLYHEDRAL 4L
/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    EnsureLoadedNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_EnsureLoadedNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry0
 * Signature: (JJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry0
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry1
 * Signature: (JJFJFJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry1
  (JNIEnv *, jobject, jlong, jlong, jfloat, jlong, jfloat, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry2
 * Signature: (JJFJFFI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry2
  (JNIEnv *, jobject, jlong, jlong, jfloat, jlong, jfloat, jfloat, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry3
 * Signature: (JJJJJJJJJJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry3
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry4
 * Signature: (JJJJ[JJJ[JJJ[J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry4
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlongArray, jlong, jlong, jlongArray, jlong, jlong, jlongArray);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry5
 * Signature: (JJJ[DJJ[DJJ[DJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry5
  (JNIEnv *, jobject, jlong, jlong, jlong, jdoubleArray, jlong, jlong, jdoubleArray, jlong, jlong, jdoubleArray, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry6
 * Signature: (JJJJ[J[[DJJ[J[[DJJ[J[[D)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry6
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlongArray, jobjectArray, jlong, jlong, jlongArray, jobjectArray, jlong, jlong, jlongArray, jobjectArray);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry7
 * Signature: (JJJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry7
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry8
 * Signature: (JJIJJJJJJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry8
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry8b
 * Signature: (JJJJJJJJIJJJJJJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry8b
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jint, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry9
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry9
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Create_RescueGeometry9b
 * Signature: (JJJJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Create_1RescueGeometry9b
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetReferenceID10
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetReferenceID10
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ReferenceID11
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ReferenceID11
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetReferenceName12
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetReferenceName12
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ReferenceName13
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_RescueGeometry_ReferenceName13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetLGRGroupName12
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetLGRGroupName12
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LGRGroupName13
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_RescueGeometry_LGRGroupName13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetLGRStartTime12
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetLGRStartTime12
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LGRStartTime13
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_RescueGeometry_LGRStartTime13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetLGREndTime12
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetLGREndTime12
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LGREndTime13
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_RescueGeometry_LGREndTime13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ProgenyHavingID14
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ProgenyHavingID14
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DropGeometry15
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_DropGeometry15
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentGeometry16
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentGeometry16
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentBUG17
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentBUG17
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LGRCount18
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_LGRCount18
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NthLGR19
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_NthLGR19
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LGRType20
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_LGRType20
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LGRGridType21
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_LGRGridType21
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentLowBound22
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentLowBound22
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentCount23
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentCount23
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentILowBound24
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentILowBound24
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentICount25
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentICount25
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentJLowBound26
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentJLowBound26
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentJCount27
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentJCount27
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentKLowBound28
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentKLowBound28
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentKCount29
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentKCount29
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    WeightLength30
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_WeightLength30
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    XWeightLength33
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_XWeightLength33
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    XWeight34
 * Signature: (J[DJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_XWeight34
  (JNIEnv *, jobject, jlong, jdoubleArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    XWeight35
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_Rescue_rjni_RescueGeometry_XWeight35
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    YWeightLength36
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_YWeightLength36
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    YWeight37
 * Signature: (J[DJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_YWeight37
  (JNIEnv *, jobject, jlong, jdoubleArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    YWeight38
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_Rescue_rjni_RescueGeometry_YWeight38
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ZWeightLength39
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ZWeightLength39
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ZWeight40
 * Signature: (J[DJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_ZWeight40
  (JNIEnv *, jobject, jlong, jdoubleArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ZWeight41
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_Rescue_rjni_RescueGeometry_ZWeight41
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    RefinedCountArray42
 * Signature: (JI[III)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_RefinedCountArray42
  (JNIEnv *, jobject, jlong, jint, jintArray, jint, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    RefinedCountArray42l
 * Signature: (JI[JJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_RefinedCountArray42l
  (JNIEnv *, jobject, jlong, jint, jlongArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    WeightBasedNodesFor43
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_WeightBasedNodesFor43
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    WeightFor44
 * Signature: (JIJ[DJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_WeightFor44
  (JNIEnv *, jobject, jlong, jint, jlong, jdoubleArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParametricMap45
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParametricMap45
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    InterfaceSurfaceDesc46
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_InterfaceSurfaceDesc46
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    InterfaceSurfaceDescCount47
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_InterfaceSurfaceDescCount47
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DropInterfaceSurfaceDesc48
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_DropInterfaceSurfaceDesc48
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    UnstructuredGrid49
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_UnstructuredGrid49
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    RadialGrid50
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_RadialGrid50
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Delete_RescueGeometry
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_Delete_1RescueGeometry
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    AnyFileTruncated52
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_AnyFileTruncated52
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Grid53
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_Grid53
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentModel54
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentModel54
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MissingValue55
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_MissingValue55
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetZValue56
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetZValue56
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetZValue57
 * Signature: (JJJ[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetZValue57
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetZValue58
 * Signature: (JJJJF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetZValue58
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetCoordinateLine59
 * Signature: (JJJFFFFFF[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetCoordinateLine59
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetCoordinatePolyLine60
 * Signature: (JJJ[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetCoordinatePolyLine60
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetCornerNode61
 * Signature: (JJJJIFFF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetCornerNode61
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetXValue62
 * Signature: (JJJJIF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetXValue62
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetYValue63
 * Signature: (JJJJIF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetYValue63
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetZValue64
 * Signature: (JJJJIF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetZValue64
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    VertexIs65
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_VertexIs65
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    VertexIs66
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_VertexIs66
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    GeometryType67
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_GeometryType67
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DemandPillar73
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_DemandPillar73
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    CornerValues76
 * Signature: (JJJJI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_Rescue_rjni_RescueGeometry_CornerValues76
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    CornerValuesLength77
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_CornerValuesLength77
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NodeValues78
 * Signature: (JJJJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_Rescue_rjni_RescueGeometry_NodeValues78
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NodeValuesLength79
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_NodeValuesLength79
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    UVWNodeValues80
 * Signature: (JJJJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_Rescue_rjni_RescueGeometry_UVWNodeValues80
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    UVWNodeValuesLength81
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_UVWNodeValuesLength81
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    UVWNodeValues282
 * Signature: (JDDD)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_Rescue_rjni_RescueGeometry_UVWNodeValues282
  (JNIEnv *, jobject, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    UVWNodeValues2Length83
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_UVWNodeValues2Length83
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ZValue84
 * Signature: (JJJJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_ZValue84
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    AllCornerValues85
 * Signature: (J[FJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_AllCornerValues85
  (JNIEnv *, jobject, jlong, jfloatArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    AllCornerValuesLength86
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_AllCornerValuesLength86
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LayerCornerValues87
 * Signature: (JJ[FJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_LayerCornerValues87
  (JNIEnv *, jobject, jlong, jlong, jfloatArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LayerCornerValuesLength88
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_LayerCornerValuesLength88
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetStairSteppedSurface89
 * Signature: (JJ[Lorg/Rescue/rjni/RescueIJKCellPair;J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetStairSteppedSurface89
  (JNIEnv *, jobject, jlong, jlong, jobjectArray, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    StairStepsFor90
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_StairStepsFor90
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    StairStepCount91
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_StairStepCount91
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NthStairSteppedFault92
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_NthStairSteppedFault92
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetSurfaceIntersection93
 * Signature: (JJ[J[JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetSurfaceIntersection93
  (JNIEnv *, jobject, jlong, jlong, jlongArray, jlongArray, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetSurfaceIntersection93i
 * Signature: (JJ[I[II)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetSurfaceIntersection93i
  (JNIEnv *, jobject, jlong, jlong, jintArray, jintArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    IntersectionFor94
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_IntersectionFor94
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NthSurfaceToGrid95
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_NthSurfaceToGrid95
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetSurfaceIntersection96
 * Signature: (JJIJJJI[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetSurfaceIntersection96
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jlong, jlong, jint, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DropRescueSurfaceCell97
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_DropRescueSurfaceCell97
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NthSurfaceCell98
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_NthSurfaceCell98
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    GeometryUnitCount99
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_GeometryUnitCount99
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NthGeometryUnit100
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_NthGeometryUnit100
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    UnitIntersect101
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_UnitIntersect101
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DropUnitIntersect102
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_DropUnitIntersect102
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DropUnitIntersect103
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_DropUnitIntersect103
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetWellboreIntersection104
 * Signature: (JJJJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetWellboreIntersection104
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DropRescueWellboreCell105
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_DropRescueWellboreCell105
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NthWellboreCell106
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_NthWellboreCell106
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    CalculateMinMax107
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_CalculateMinMax107
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MinMaxDirty108
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_MinMaxDirty108
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MinX109
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_MinX109
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MaxX110
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_MaxX110
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MinY111
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_MinY111
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MaxY112
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_MaxY112
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MinZ113
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_MinZ113
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MaxZ114
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_MaxZ114
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    PropertyCount115
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_PropertyCount115
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    NthRescueProperty116
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_NthRescueProperty116
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    PropertyIdentifiedBy117
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_PropertyIdentifiedBy117
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    PropertyNamed118
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_PropertyNamed118
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DropRescueProperty119
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_DropRescueProperty119
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetKLayerID120
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_SetKLayerID120
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    KLayerID121
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_KLayerID121
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentBlockUnit122
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentBlockUnit122
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ParentGeobodyPart123
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ParentGeobodyPart123
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    IsProportional124
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_IsProportional124
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    TopReferenceSurface125
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_TopReferenceSurface125
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    BottomReferenceSurface126
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_BottomReferenceSurface126
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    TopOffset127
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_TopOffset127
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    BottomOffset128
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_BottomOffset128
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    IsReferenced129
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_IsReferenced129
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ReferenceSurface130
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_ReferenceSurface130
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SurfaceOffset131
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_SurfaceOffset131
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    KLayerThickness132
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueGeometry_KLayerThickness132
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LapType133
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_LapType133
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Version134
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_Version134
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SetCellStatus135
 * Signature: (JJJJI)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_SetCellStatus135
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    CellStatus136
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_CellStatus136
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    IsOfType137
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_IsOfType137
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    IsLoaded138
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_IsLoaded138
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    FileTruncated139
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_FileTruncated139
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Load140
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_Load140
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    Unload141
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_Unload141
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    HasChanged142
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeometry_HasChanged142
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    MarkChanged143
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_MarkChanged143
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    LoadRefSurface144
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeometry_LoadRefSurface144
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    WireFrame145
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_WireFrame145
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ObjectCounts146
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_Rescue_rjni_RescueGeometry_ObjectCounts146
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    ObjectCountsLength147
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueGeometry_ObjectCountsLength147
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    SurfaceToGridCount148
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_SurfaceToGridCount148
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    GetColor149
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_GetColor149
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DataContainers150
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_DataContainers150
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeometry
 * Method:    DemandDataContainers151
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeometry_DemandDataContainers151
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
