/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetString */

#ifndef _Included_org_Rescue_rjni_cSetString
#define _Included_org_Rescue_rjni_cSetString
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetString
 * Method:    Create_cSetString0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetString_Create_1cSetString0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetString
 * Method:    Delete_cSetString
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetString_Delete_1cSetString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetString
 * Method:    AddTo2
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetString_AddTo2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetString
 * Method:    RemoveFrom3
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetString_RemoveFrom3
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetString
 * Method:    NthObject4
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_cSetString_NthObject4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetString
 * Method:    Count5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetString_Count5
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetString
 * Method:    Contains6
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetString_Contains6
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetString
 * Method:    EmptySelf7
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetString_EmptySelf7
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
