/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueArrayFragment */

#ifndef _Included_org_Rescue_rjni_RescueArrayFragment
#define _Included_org_Rescue_rjni_RescueArrayFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    Dimensions0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueArrayFragment_Dimensions0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    ILowBound1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragment_ILowBound1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    ICount2
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragment_ICount2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    JLowBound3
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragment_JLowBound3
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    JCount4
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragment_JCount4
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    KLowBound5
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragment_KLowBound5
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    KCount6
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragment_KCount6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    NodeCount7
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragment_NodeCount7
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragment
 * Method:    Delete_RescueArrayFragment
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayFragment_Delete_1RescueArrayFragment
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
