/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueCoordinatePolyLine */

#ifndef _Included_org_Rescue_rjni_RescueCoordinatePolyLine
#define _Included_org_Rescue_rjni_RescueCoordinatePolyLine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueCoordinatePolyLine
 * Method:    Delete_RescueCoordinatePolyLine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueCoordinatePolyLine_Delete_1RescueCoordinatePolyLine
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
