/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueStreamReporter */

#ifndef _Included_org_Rescue_rjni_RescueStreamReporter
#define _Included_org_Rescue_rjni_RescueStreamReporter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueStreamReporter
 * Method:    Create_RescueStreamReporter1
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueStreamReporter_Create_1RescueStreamReporter1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
