/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueArrayDouble */

#ifndef _Included_org_Rescue_rjni_RescueArrayDouble
#define _Included_org_Rescue_rjni_RescueArrayDouble
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueArrayDouble_R_TOMBSTONE
#define org_Rescue_rjni_RescueArrayDouble_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueObject
#define org_Rescue_rjni_RescueArrayDouble_R_RescueObject 1L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueModel
#define org_Rescue_rjni_RescueArrayDouble_R_RescueModel 2L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueBlock
#define org_Rescue_rjni_RescueArrayDouble_R_RescueBlock 3L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueUnit
#define org_Rescue_rjni_RescueArrayDouble_R_RescueUnit 4L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueHorizon
#define org_Rescue_rjni_RescueArrayDouble_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueSection
#define org_Rescue_rjni_RescueArrayDouble_R_RescueSection 6L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueBlockUnit
#define org_Rescue_rjni_RescueArrayDouble_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescueArrayDouble_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueProperty
#define org_Rescue_rjni_RescueArrayDouble_R_RescueProperty 9L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePropertyGroup
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescueArrayDouble_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueWellbore
#define org_Rescue_rjni_RescueArrayDouble_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueWellboreProperty
#define org_Rescue_rjni_RescueArrayDouble_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueGrid
#define org_Rescue_rjni_RescueArrayDouble_R_RescueGrid 14L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueGridAxis
#define org_Rescue_rjni_RescueArrayDouble_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueArray
#define org_Rescue_rjni_RescueArrayDouble_R_RescueArray 16L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueTripletArray
#define org_Rescue_rjni_RescueArrayDouble_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescueArrayDouble_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueVertex
#define org_Rescue_rjni_RescueArrayDouble_R_RescueVertex 19L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescueArrayDouble_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueSurface
#define org_Rescue_rjni_RescueArrayDouble_R_RescueSurface 21L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueDoubletArray
#define org_Rescue_rjni_RescueArrayDouble_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueTrimVertex
#define org_Rescue_rjni_RescueArrayDouble_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueEdgeSet
#define org_Rescue_rjni_RescueArrayDouble_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueTrimEdge
#define org_Rescue_rjni_RescueArrayDouble_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLine
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNode
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueGeometry
#define org_Rescue_rjni_RescueArrayDouble_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueSurfaceCell
#define org_Rescue_rjni_RescueArrayDouble_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueWellboreSampling
#define org_Rescue_rjni_RescueArrayDouble_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueWellboreSurface
#define org_Rescue_rjni_RescueArrayDouble_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueWellboreCell
#define org_Rescue_rjni_RescueArrayDouble_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueReferenceSurface
#define org_Rescue_rjni_RescueArrayDouble_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueLookup
#define org_Rescue_rjni_RescueArrayDouble_R_RescueLookup 35L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueLookupItem
#define org_Rescue_rjni_RescueArrayDouble_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueLookupString
#define org_Rescue_rjni_RescueArrayDouble_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueLookupTable
#define org_Rescue_rjni_RescueArrayDouble_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueArrayDouble
#define org_Rescue_rjni_RescueArrayDouble_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueArrayByte
#define org_Rescue_rjni_RescueArrayDouble_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueArrayShort
#define org_Rescue_rjni_RescueArrayDouble_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueTrimLoop
#define org_Rescue_rjni_RescueArrayDouble_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueArrayFloat
#define org_Rescue_rjni_RescueArrayDouble_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueMacroVolume
#define org_Rescue_rjni_RescueArrayDouble_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescueArrayDouble_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescueArrayDouble_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueBitArray
#define org_Rescue_rjni_RescueArrayDouble_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueColor
#define org_Rescue_rjni_RescueArrayDouble_R_RescueColor 48L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueHistory
#define org_Rescue_rjni_RescueArrayDouble_R_RescueHistory 49L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueHistoryObject
#define org_Rescue_rjni_RescueArrayDouble_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueArray2dVector
#define org_Rescue_rjni_RescueArrayDouble_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueArray3dVector
#define org_Rescue_rjni_RescueArrayDouble_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueColorTable
#define org_Rescue_rjni_RescueArrayDouble_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueColorTableList
#define org_Rescue_rjni_RescueArrayDouble_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueGeobody
#define org_Rescue_rjni_RescueArrayDouble_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueGeobodyPart
#define org_Rescue_rjni_RescueArrayDouble_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueGeobodySurface
#define org_Rescue_rjni_RescueArrayDouble_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescueArrayDouble_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescueArrayDouble_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueIJSurface
#define org_Rescue_rjni_RescueArrayDouble_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueCellShape
#define org_Rescue_rjni_RescueArrayDouble_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueEventDescr
#define org_Rescue_rjni_RescueArrayDouble_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueLogicalOrder
#define org_Rescue_rjni_RescueArrayDouble_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueFaultIntersection
#define org_Rescue_rjni_RescueArrayDouble_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueWireframeStub
#define org_Rescue_rjni_RescueArrayDouble_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineStub
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescueArrayDouble_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescueArrayDouble_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescueArrayDouble_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueWireframe
#define org_Rescue_rjni_RescueArrayDouble_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueWireframeOwner
#define org_Rescue_rjni_RescueArrayDouble_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueArrayInt
#define org_Rescue_rjni_RescueArrayDouble_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueGeometryUnit
#define org_Rescue_rjni_RescueArrayDouble_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueReservoir
#define org_Rescue_rjni_RescueArrayDouble_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescueArrayDouble_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescueArrayDouble_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescueArrayDouble_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescueArrayDouble_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescueArrayDouble_R_RescueDataContainer
#define org_Rescue_rjni_RescueArrayDouble_R_RescueDataContainer 82L
/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    Delete_RescueArrayDouble
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayDouble_Delete_1RescueArrayDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    NullValue1
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueArrayDouble_NullValue1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    Value2
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_Rescue_rjni_RescueArrayDouble_Value2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    ValueLength3
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayDouble_ValueLength3
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    AllValues4
 * Signature: (J[DJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayDouble_AllValues4
  (JNIEnv *, jobject, jlong, jdoubleArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    SetValue5
 * Signature: (JD[D)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayDouble_SetValue5
  (JNIEnv *, jobject, jlong, jdouble, jdoubleArray);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    IsLoaded7
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueArrayDouble_IsLoaded7
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    MinValue8
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueArrayDouble_MinValue8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    MaxValue9
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueArrayDouble_MaxValue9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    Load10
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayDouble_Load10
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    Load11
 * Signature: (JJJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayDouble_Load11
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    Create12
 * Signature: (JJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayDouble_Create12
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    Create13
 * Signature: (JJJJJJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayDouble_Create13
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayDouble
 * Method:    IsOfType14
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueArrayDouble_IsOfType14
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
