/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescueArrayFragment */

#ifndef _Included_org_Rescue_rjni_cSetRescueArrayFragment
#define _Included_org_Rescue_rjni_cSetRescueArrayFragment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescueArrayFragment
 * Method:    Create_cSetRescueArrayFragment0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueArrayFragment_Create_1cSetRescueArrayFragment0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescueArrayFragment
 * Method:    Delete_cSetRescueArrayFragment
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueArrayFragment_Delete_1cSetRescueArrayFragment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueArrayFragment
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueArrayFragment_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueArrayFragment
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueArrayFragment_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueArrayFragment
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueArrayFragment_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueArrayFragment
 * Method:    NthObject5x
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_org_Rescue_rjni_cSetRescueArrayFragment_NthObject5x
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueArrayFragment
 * Method:    Count6
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueArrayFragment_Count6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueArrayFragment
 * Method:    EmptySelf7
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueArrayFragment_EmptySelf7
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
