/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescuePoint */

#ifndef _Included_org_Rescue_rjni_RescuePoint
#define _Included_org_Rescue_rjni_RescuePoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    Create_RescuePoint0
 * Signature: (FFF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePoint_Create_1RescuePoint0
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    Create_RescuePoint1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePoint_Create_1RescuePoint1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    Delete_RescuePoint
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePoint_Delete_1RescuePoint
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    X4
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePoint_X4
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    Y5
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePoint_Y5
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    Z6
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePoint_Z6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    SetX7
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePoint_SetX7
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    SetY8
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePoint_SetY8
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePoint
 * Method:    SetZ9
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePoint_SetZ9
  (JNIEnv *, jobject, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
