/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueCoordinateSystem */

#ifndef _Included_org_Rescue_rjni_RescueCoordinateSystem
#define _Included_org_Rescue_rjni_RescueCoordinateSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueCoordinateSystem_R_TOMBSTONE
#define org_Rescue_rjni_RescueCoordinateSystem_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueObject
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueObject 1L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueModel
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueModel 2L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueBlock
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueBlock 3L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueUnit
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueUnit 4L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueHorizon
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueSection
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueSection 6L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueBlockUnit
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueProperty
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueProperty 9L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePropertyGroup
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellbore
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellboreProperty
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueGrid
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueGrid 14L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueGridAxis
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueArray
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueArray 16L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueTripletArray
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueVertex
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueVertex 19L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueSurface
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueSurface 21L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueDoubletArray
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimVertex
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueEdgeSet
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimEdge
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLine
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNode
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeometry
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueSurfaceCell
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellboreSampling
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellboreSurface
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellboreCell
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueReferenceSurface
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueLookup
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueLookup 35L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueLookupItem
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueLookupString
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueLookupTable
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayDouble
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayByte
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayShort
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimLoop
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayFloat
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueMacroVolume
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueBitArray
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueColor
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueColor 48L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueHistory
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueHistory 49L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueHistoryObject
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueArray2dVector
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueArray3dVector
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueColorTable
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueColorTableList
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeobody
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeobodyPart
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeobodySurface
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueIJSurface
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueCellShape
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueEventDescr
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueLogicalOrder
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueFaultIntersection
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueWireframeStub
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineStub
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueWireframe
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueWireframeOwner
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayInt
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeometryUnit
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueReservoir
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescueCoordinateSystem_R_RescueDataContainer
#define org_Rescue_rjni_RescueCoordinateSystem_R_RescueDataContainer 82L
#undef org_Rescue_rjni_RescueCoordinateSystem_LUF
#define org_Rescue_rjni_RescueCoordinateSystem_LUF 0L
#undef org_Rescue_rjni_RescueCoordinateSystem_LUB
#define org_Rescue_rjni_RescueCoordinateSystem_LUB 1L
#undef org_Rescue_rjni_RescueCoordinateSystem_LDF
#define org_Rescue_rjni_RescueCoordinateSystem_LDF 2L
#undef org_Rescue_rjni_RescueCoordinateSystem_LDB
#define org_Rescue_rjni_RescueCoordinateSystem_LDB 3L
#undef org_Rescue_rjni_RescueCoordinateSystem_RUF
#define org_Rescue_rjni_RescueCoordinateSystem_RUF 4L
#undef org_Rescue_rjni_RescueCoordinateSystem_RUB
#define org_Rescue_rjni_RescueCoordinateSystem_RUB 5L
#undef org_Rescue_rjni_RescueCoordinateSystem_RDF
#define org_Rescue_rjni_RescueCoordinateSystem_RDF 6L
#undef org_Rescue_rjni_RescueCoordinateSystem_RDB
#define org_Rescue_rjni_RescueCoordinateSystem_RDB 7L
/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    Create_RescueCoordinateSystem0
 * Signature: (JLjava/lang/String;IJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIDDDDDDDD)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_Create_1RescueCoordinateSystem0
  (JNIEnv *, jobject, jlong, jstring, jint, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jint, jint, jint, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    Dimensions1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_Dimensions1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    Axis2
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_Axis2
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    AxisIdentifiedBy3
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_AxisIdentifiedBy3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    Vertex4
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_Vertex4
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    SetVertex5
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_SetVertex5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    Name6
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_Name6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    OrientationIs7
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_OrientationIs7
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    InSys8
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_InSys8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    InZone9
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_InZone9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    InUnit10
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_InUnit10
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    InSpheroid11
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_InSpheroid11
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    SemiMajorAxis12
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_SemiMajorAxis12
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    EccentricityOrSemiMinorAxis13
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_EccentricityOrSemiMinorAxis13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    StandardLat14
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_StandardLat14
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    SecondLat15
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_SecondLat15
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    CentralLong16
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_CentralLong16
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    LatOrigin17
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_LatOrigin17
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    FalseEasting18
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_FalseEasting18
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    FalseNorthing19
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_FalseNorthing19
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    NdxOf20
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_NdxOf20
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    Context21
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_Context21
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    IsOfType22
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_IsOfType22
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    Delete_RescueCoordinateSystem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_Delete_1RescueCoordinateSystem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    PublicEPSG1
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_PublicEPSG1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueCoordinateSystem
 * Method:    SetPublicEPSG2
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueCoordinateSystem_SetPublicEPSG2
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
