/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueTriangleFace */

#ifndef _Included_org_Rescue_rjni_RescueTriangleFace
#define _Included_org_Rescue_rjni_RescueTriangleFace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueTriangleFace
 * Method:    Create_RescueTriangleFace0
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTriangleFace_Create_1RescueTriangleFace0
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTriangleFace
 * Method:    Create_RescueTriangleFace1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTriangleFace_Create_1RescueTriangleFace1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTriangleFace
 * Method:    Delete_RescueTriangleFace
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTriangleFace_Delete_1RescueTriangleFace
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTriangleFace
 * Method:    NthVertex3
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTriangleFace_NthVertex3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTriangleFace
 * Method:    CrossFace4
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTriangleFace_CrossFace4
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
