/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueSplineCoef */

#ifndef _Included_org_Rescue_rjni_RescueSplineCoef
#define _Included_org_Rescue_rjni_RescueSplineCoef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    Create_RescueSplineCoef0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueSplineCoef_Create_1RescueSplineCoef0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    B1
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSplineCoef_B1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    C2
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSplineCoef_C2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    D3
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSplineCoef_D3
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    SetB4
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSplineCoef_SetB4
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    SetC5
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSplineCoef_SetC5
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    SetD6
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueSplineCoef_SetD6
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    interpolate7
 * Signature: (JFF)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSplineCoef_interpolate7
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueSplineCoef
 * Method:    derive8
 * Signature: (JF)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueSplineCoef_derive8
  (JNIEnv *, jobject, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
