/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescuePolyLineNodeBUG */

#ifndef _Included_org_Rescue_rjni_cSetRescuePolyLineNodeBUG
#define _Included_org_Rescue_rjni_cSetRescuePolyLineNodeBUG
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    Create_cSetRescuePolyLineNodeBUG0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_Create_1cSetRescuePolyLineNodeBUG0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    Delete_cSetRescuePolyLineNodeBUG
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_Delete_1cSetRescuePolyLineNodeBUG
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    NthObject5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_NthObject5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    ObjectNamed6
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_ObjectNamed6
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    ObjectIdentifiedBy7
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_ObjectIdentifiedBy7
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    Count8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_Count8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    EmptySelf9
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_EmptySelf9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescuePolyLineNodeBUG
 * Method:    Relink12
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescuePolyLineNodeBUG_Relink12
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
