/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueBlockUnit */

#ifndef _Included_org_Rescue_rjni_RescueBlockUnit
#define _Included_org_Rescue_rjni_RescueBlockUnit
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueBlockUnit_R_TOMBSTONE
#define org_Rescue_rjni_RescueBlockUnit_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueObject
#define org_Rescue_rjni_RescueBlockUnit_R_RescueObject 1L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueModel
#define org_Rescue_rjni_RescueBlockUnit_R_RescueModel 2L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueBlock
#define org_Rescue_rjni_RescueBlockUnit_R_RescueBlock 3L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueUnit
#define org_Rescue_rjni_RescueBlockUnit_R_RescueUnit 4L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueHorizon
#define org_Rescue_rjni_RescueBlockUnit_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueSection
#define org_Rescue_rjni_RescueBlockUnit_R_RescueSection 6L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueBlockUnit
#define org_Rescue_rjni_RescueBlockUnit_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescueBlockUnit_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueProperty
#define org_Rescue_rjni_RescueBlockUnit_R_RescueProperty 9L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePropertyGroup
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescueBlockUnit_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueWellbore
#define org_Rescue_rjni_RescueBlockUnit_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueWellboreProperty
#define org_Rescue_rjni_RescueBlockUnit_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueGrid
#define org_Rescue_rjni_RescueBlockUnit_R_RescueGrid 14L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueGridAxis
#define org_Rescue_rjni_RescueBlockUnit_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueArray
#define org_Rescue_rjni_RescueBlockUnit_R_RescueArray 16L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueTripletArray
#define org_Rescue_rjni_RescueBlockUnit_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescueBlockUnit_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueVertex
#define org_Rescue_rjni_RescueBlockUnit_R_RescueVertex 19L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescueBlockUnit_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueSurface
#define org_Rescue_rjni_RescueBlockUnit_R_RescueSurface 21L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueDoubletArray
#define org_Rescue_rjni_RescueBlockUnit_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueTrimVertex
#define org_Rescue_rjni_RescueBlockUnit_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueEdgeSet
#define org_Rescue_rjni_RescueBlockUnit_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueTrimEdge
#define org_Rescue_rjni_RescueBlockUnit_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLine
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNode
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueGeometry
#define org_Rescue_rjni_RescueBlockUnit_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueSurfaceCell
#define org_Rescue_rjni_RescueBlockUnit_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueWellboreSampling
#define org_Rescue_rjni_RescueBlockUnit_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueWellboreSurface
#define org_Rescue_rjni_RescueBlockUnit_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueWellboreCell
#define org_Rescue_rjni_RescueBlockUnit_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueReferenceSurface
#define org_Rescue_rjni_RescueBlockUnit_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueLookup
#define org_Rescue_rjni_RescueBlockUnit_R_RescueLookup 35L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueLookupItem
#define org_Rescue_rjni_RescueBlockUnit_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueLookupString
#define org_Rescue_rjni_RescueBlockUnit_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueLookupTable
#define org_Rescue_rjni_RescueBlockUnit_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueArrayDouble
#define org_Rescue_rjni_RescueBlockUnit_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueArrayByte
#define org_Rescue_rjni_RescueBlockUnit_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueArrayShort
#define org_Rescue_rjni_RescueBlockUnit_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueTrimLoop
#define org_Rescue_rjni_RescueBlockUnit_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueArrayFloat
#define org_Rescue_rjni_RescueBlockUnit_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueMacroVolume
#define org_Rescue_rjni_RescueBlockUnit_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescueBlockUnit_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescueBlockUnit_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueBitArray
#define org_Rescue_rjni_RescueBlockUnit_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueColor
#define org_Rescue_rjni_RescueBlockUnit_R_RescueColor 48L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueHistory
#define org_Rescue_rjni_RescueBlockUnit_R_RescueHistory 49L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueHistoryObject
#define org_Rescue_rjni_RescueBlockUnit_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueArray2dVector
#define org_Rescue_rjni_RescueBlockUnit_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueArray3dVector
#define org_Rescue_rjni_RescueBlockUnit_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueColorTable
#define org_Rescue_rjni_RescueBlockUnit_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueColorTableList
#define org_Rescue_rjni_RescueBlockUnit_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueGeobody
#define org_Rescue_rjni_RescueBlockUnit_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueGeobodyPart
#define org_Rescue_rjni_RescueBlockUnit_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueGeobodySurface
#define org_Rescue_rjni_RescueBlockUnit_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescueBlockUnit_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescueBlockUnit_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueIJSurface
#define org_Rescue_rjni_RescueBlockUnit_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueCellShape
#define org_Rescue_rjni_RescueBlockUnit_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueEventDescr
#define org_Rescue_rjni_RescueBlockUnit_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueLogicalOrder
#define org_Rescue_rjni_RescueBlockUnit_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueFaultIntersection
#define org_Rescue_rjni_RescueBlockUnit_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueWireframeStub
#define org_Rescue_rjni_RescueBlockUnit_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineStub
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescueBlockUnit_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescueBlockUnit_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescueBlockUnit_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueWireframe
#define org_Rescue_rjni_RescueBlockUnit_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueWireframeOwner
#define org_Rescue_rjni_RescueBlockUnit_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueArrayInt
#define org_Rescue_rjni_RescueBlockUnit_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueGeometryUnit
#define org_Rescue_rjni_RescueBlockUnit_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueReservoir
#define org_Rescue_rjni_RescueBlockUnit_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescueBlockUnit_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescueBlockUnit_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescueBlockUnit_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescueBlockUnit_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescueBlockUnit_R_RescueDataContainer
#define org_Rescue_rjni_RescueBlockUnit_R_RescueDataContainer 82L
/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Create_RescueBlockUnit0
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Create_1RescueBlockUnit0
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Create_RescueBlockUnit1
 * Signature: (IJJFFJJFFJJFFJJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Create_1RescueBlockUnit1
  (JNIEnv *, jobject, jint, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Create_RescueBlockUnit2
 * Signature: (IJJFFJJFFJJJJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Create_1RescueBlockUnit2
  (JNIEnv *, jobject, jint, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jlong, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Create_RescueBlockUnit3
 * Signature: (IJJFFJJFFJJJJFJFJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Create_1RescueBlockUnit3
  (JNIEnv *, jobject, jint, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jlong, jlong, jfloat, jlong, jfloat, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Create_RescueBlockUnit4
 * Signature: (IJJFFJJFFJJJJFJFFI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Create_1RescueBlockUnit4
  (JNIEnv *, jobject, jint, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jlong, jlong, jfloat, jlong, jfloat, jfloat, jint);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Delete_RescueBlockUnit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Delete_1RescueBlockUnit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Unit6
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Unit6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Block7
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Block7
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    ParentModel8
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_ParentModel8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    SurfaceAboveMe9
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_SurfaceAboveMe9
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    SurfaceBelowMe10
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_SurfaceBelowMe10
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    SetSurfaceAboveMe11
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockUnit_SetSurfaceAboveMe11
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    SetSurfaceBelowMe12
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockUnit_SetSurfaceBelowMe12
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    AddMacroVolume13
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_AddMacroVolume13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    DropMacroVolume14
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockUnit_DropMacroVolume14
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    NthMacroVolume15
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_NthMacroVolume15
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    MacroVolumeIdentifiedBy16
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_MacroVolumeIdentifiedBy16
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    BlockUnitSideIdentifiedBy17
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_BlockUnitSideIdentifiedBy17
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    AddPropertyGroup18
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockUnit_AddPropertyGroup18
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    DeletePropertyGroup19
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueBlockUnit_DeletePropertyGroup19
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    NthPropertyGroup20
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_NthPropertyGroup20
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    BlockUnitGrid21
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_BlockUnitGrid21
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    GridGeometry22
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_GridGeometry22
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    GeometryCount23
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_GeometryCount23
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    AddGeometry24
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockUnit_AddGeometry24
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    DropGeometry25
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockUnit_DropGeometry25
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    PropertyCount26
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_PropertyCount26
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    CountOfPropertyGroup27
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_CountOfPropertyGroup27
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    CountOfVolumes28
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_CountOfVolumes28
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    CountOfGeobodies29
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_CountOfGeobodies29
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    NthPart30
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_NthPart30
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    GeometryIdentifiedBy31
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_GeometryIdentifiedBy31
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    AnyFileTruncated32
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueBlockUnit_AnyFileTruncated32
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    SetColor34
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueBlockUnit_SetColor34
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    Color35
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_Color35
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    PropertyIdentifiedBy36
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueBlockUnit_PropertyIdentifiedBy36
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueBlockUnit
 * Method:    IsOfType37
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueBlockUnit_IsOfType37
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
