/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescuePillar */

#ifndef _Included_org_Rescue_rjni_RescuePillar
#define _Included_org_Rescue_rjni_RescuePillar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    Create_RescuePillar0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_Create_1RescuePillar0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    Delete_RescuePillar
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_Delete_1RescuePillar
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    VertexIs2
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescuePillar_VertexIs2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    NodeValues7
 * Signature: (JJJJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_Rescue_rjni_RescuePillar_NodeValues7
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    NodeValuesLength8
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescuePillar_NodeValuesLength8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    KValue9
 * Signature: (JJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePillar_KValue9
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    KValueR9
 * Signature: (JJJ)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescuePillar_KValueR9
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    ZValue10
 * Signature: (JJF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_ZValue10
  (JNIEnv *, jobject, jlong, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    ZStack11
 * Signature: (JJ[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_ZStack11
  (JNIEnv *, jobject, jlong, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    ZStack12
 * Signature: (JJJ[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_ZStack12
  (JNIEnv *, jobject, jlong, jlong, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    IsSplit13
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescuePillar_IsSplit13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    IsVertical14
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescuePillar_IsVertical14
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    TopTruncation15
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_TopTruncation15
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    BaseTruncation16
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_BaseTruncation16
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    SetTopTruncation17
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_SetTopTruncation17
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    SetBaseTruncation18
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_SetBaseTruncation18
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    AddControlPoint19
 * Signature: (JFFF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_AddControlPoint19
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    rebuildSplineCoeffs20
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_rebuildSplineCoeffs20
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    AddControlPoint21
 * Signature: (JFFFFFFFFF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescuePillar_AddControlPoint21
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getByZ22
 * Signature: (JF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getByZ22
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getMinTangent23
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getMinTangent23
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getMaxTangent24
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getMaxTangent24
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getNumCtrlPoints25
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getNumCtrlPoints25
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getMinCtrlPoint26
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getMinCtrlPoint26
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getMaxCtrlPoint27
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getMaxCtrlPoint27
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getCtrlPointAt28
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getCtrlPointAt28
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getXSplineCoefAt29
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getXSplineCoefAt29
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescuePillar
 * Method:    getYSplineCoefAt30
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescuePillar_getYSplineCoefAt30
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
