/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_cSetRescueSOctTreeNode */

#ifndef _Included_org_Rescue_rjni_cSetRescueSOctTreeNode
#define _Included_org_Rescue_rjni_cSetRescueSOctTreeNode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_cSetRescueSOctTreeNode
 * Method:    Create_cSetRescueSOctTreeNode0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueSOctTreeNode_Create_1cSetRescueSOctTreeNode0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_cSetRescueSOctTreeNode
 * Method:    Delete_cSetRescueSOctTreeNode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueSOctTreeNode_Delete_1cSetRescueSOctTreeNode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueSOctTreeNode
 * Method:    AddTo2
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueSOctTreeNode_AddTo2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueSOctTreeNode
 * Method:    RemoveFrom3
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueSOctTreeNode_RemoveFrom3
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueSOctTreeNode
 * Method:    RemoveFrom4
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_cSetRescueSOctTreeNode_RemoveFrom4
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueSOctTreeNode
 * Method:    NthObject5
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueSOctTreeNode_NthObject5
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueSOctTreeNode
 * Method:    Count6
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_cSetRescueSOctTreeNode_Count6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_cSetRescueSOctTreeNode
 * Method:    EmptySelf7
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_cSetRescueSOctTreeNode_EmptySelf7
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
