/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueArrayFragmentShort */

#ifndef _Included_org_Rescue_rjni_RescueArrayFragmentShort
#define _Included_org_Rescue_rjni_RescueArrayFragmentShort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueArrayFragmentShort
 * Method:    Delete_RescueArrayFragmentShort
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayFragmentShort_Delete_1RescueArrayFragmentShort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragmentShort
 * Method:    ValueLength1
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueArrayFragmentShort_ValueLength1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragmentShort
 * Method:    Value2
 * Signature: (J)[C
 */
JNIEXPORT jcharArray JNICALL Java_org_Rescue_rjni_RescueArrayFragmentShort_Value2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueArrayFragmentShort
 * Method:    SetValue3
 * Signature: (J[C)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueArrayFragmentShort_SetValue3
  (JNIEnv *, jobject, jlong, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
