/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueTripletArray */

#ifndef _Included_org_Rescue_rjni_RescueTripletArray
#define _Included_org_Rescue_rjni_RescueTripletArray
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueTripletArray_R_TOMBSTONE
#define org_Rescue_rjni_RescueTripletArray_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueObject
#define org_Rescue_rjni_RescueTripletArray_R_RescueObject 1L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueModel
#define org_Rescue_rjni_RescueTripletArray_R_RescueModel 2L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueBlock
#define org_Rescue_rjni_RescueTripletArray_R_RescueBlock 3L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueUnit
#define org_Rescue_rjni_RescueTripletArray_R_RescueUnit 4L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueHorizon
#define org_Rescue_rjni_RescueTripletArray_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueSection
#define org_Rescue_rjni_RescueTripletArray_R_RescueSection 6L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueBlockUnit
#define org_Rescue_rjni_RescueTripletArray_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescueTripletArray_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueProperty
#define org_Rescue_rjni_RescueTripletArray_R_RescueProperty 9L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePropertyGroup
#define org_Rescue_rjni_RescueTripletArray_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescueTripletArray_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueWellbore
#define org_Rescue_rjni_RescueTripletArray_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueWellboreProperty
#define org_Rescue_rjni_RescueTripletArray_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueGrid
#define org_Rescue_rjni_RescueTripletArray_R_RescueGrid 14L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueGridAxis
#define org_Rescue_rjni_RescueTripletArray_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueArray
#define org_Rescue_rjni_RescueTripletArray_R_RescueArray 16L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueTripletArray
#define org_Rescue_rjni_RescueTripletArray_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescueTripletArray_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueVertex
#define org_Rescue_rjni_RescueTripletArray_R_RescueVertex 19L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescueTripletArray_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueSurface
#define org_Rescue_rjni_RescueTripletArray_R_RescueSurface 21L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueDoubletArray
#define org_Rescue_rjni_RescueTripletArray_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueTrimVertex
#define org_Rescue_rjni_RescueTripletArray_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueEdgeSet
#define org_Rescue_rjni_RescueTripletArray_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueTrimEdge
#define org_Rescue_rjni_RescueTripletArray_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePolyLine
#define org_Rescue_rjni_RescueTripletArray_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNode
#define org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueGeometry
#define org_Rescue_rjni_RescueTripletArray_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueSurfaceCell
#define org_Rescue_rjni_RescueTripletArray_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueWellboreSampling
#define org_Rescue_rjni_RescueTripletArray_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueWellboreSurface
#define org_Rescue_rjni_RescueTripletArray_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueWellboreCell
#define org_Rescue_rjni_RescueTripletArray_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueReferenceSurface
#define org_Rescue_rjni_RescueTripletArray_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueLookup
#define org_Rescue_rjni_RescueTripletArray_R_RescueLookup 35L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueLookupItem
#define org_Rescue_rjni_RescueTripletArray_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueLookupString
#define org_Rescue_rjni_RescueTripletArray_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueLookupTable
#define org_Rescue_rjni_RescueTripletArray_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueArrayDouble
#define org_Rescue_rjni_RescueTripletArray_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueArrayByte
#define org_Rescue_rjni_RescueTripletArray_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueArrayShort
#define org_Rescue_rjni_RescueTripletArray_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueTrimLoop
#define org_Rescue_rjni_RescueTripletArray_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueArrayFloat
#define org_Rescue_rjni_RescueTripletArray_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueMacroVolume
#define org_Rescue_rjni_RescueTripletArray_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescueTripletArray_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescueTripletArray_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueBitArray
#define org_Rescue_rjni_RescueTripletArray_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueColor
#define org_Rescue_rjni_RescueTripletArray_R_RescueColor 48L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueHistory
#define org_Rescue_rjni_RescueTripletArray_R_RescueHistory 49L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueHistoryObject
#define org_Rescue_rjni_RescueTripletArray_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueArray2dVector
#define org_Rescue_rjni_RescueTripletArray_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueArray3dVector
#define org_Rescue_rjni_RescueTripletArray_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueColorTable
#define org_Rescue_rjni_RescueTripletArray_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueColorTableList
#define org_Rescue_rjni_RescueTripletArray_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueGeobody
#define org_Rescue_rjni_RescueTripletArray_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueGeobodyPart
#define org_Rescue_rjni_RescueTripletArray_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueGeobodySurface
#define org_Rescue_rjni_RescueTripletArray_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescueTripletArray_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescueTripletArray_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueIJSurface
#define org_Rescue_rjni_RescueTripletArray_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueCellShape
#define org_Rescue_rjni_RescueTripletArray_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueEventDescr
#define org_Rescue_rjni_RescueTripletArray_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueLogicalOrder
#define org_Rescue_rjni_RescueTripletArray_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueFaultIntersection
#define org_Rescue_rjni_RescueTripletArray_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueWireframeStub
#define org_Rescue_rjni_RescueTripletArray_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineStub
#define org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescueTripletArray_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescueTripletArray_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescueTripletArray_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueWireframe
#define org_Rescue_rjni_RescueTripletArray_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueWireframeOwner
#define org_Rescue_rjni_RescueTripletArray_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueArrayInt
#define org_Rescue_rjni_RescueTripletArray_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueGeometryUnit
#define org_Rescue_rjni_RescueTripletArray_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueReservoir
#define org_Rescue_rjni_RescueTripletArray_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescueTripletArray_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescueTripletArray_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescueTripletArray_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescueTripletArray_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescueTripletArray_R_RescueDataContainer
#define org_Rescue_rjni_RescueTripletArray_R_RescueDataContainer 82L
/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    EnsureLoadedNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_EnsureLoadedNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    Create_RescueTripletArray0
 * Signature: (JJFJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTripletArray_Create_1RescueTripletArray0
  (JNIEnv *, jobject, jlong, jlong, jfloat, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    Create_RescueTripletArray1
 * Signature: (JF[FJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTripletArray_Create_1RescueTripletArray1
  (JNIEnv *, jobject, jlong, jfloat, jfloatArray, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    Delete_RescueTripletArray
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_Delete_1RescueTripletArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    Grid3
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTripletArray_Grid3
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    MissingValue4
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_Rescue_rjni_RescueTripletArray_MissingValue4
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    SetValue5
 * Signature: (JF[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_SetValue5
  (JNIEnv *, jobject, jlong, jfloat, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    AssignXValue6
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_AssignXValue6
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    AssignYValue7
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_AssignYValue7
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    AssignZValue8
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_AssignZValue8
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    SetXValue9
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_SetXValue9
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    SetYValue10
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_SetYValue10
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    SetZValue11
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_SetZValue11
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    RescueGetXValue12
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_Rescue_rjni_RescueTripletArray_RescueGetXValue12
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    RescueGetYValue13
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_Rescue_rjni_RescueTripletArray_RescueGetYValue13
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    RescueGetZValue14
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_org_Rescue_rjni_RescueTripletArray_RescueGetZValue14
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    RescueGetXValueLength15
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTripletArray_RescueGetXValueLength15
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    RescueGetYValueLength16
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTripletArray_RescueGetYValueLength16
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    RescueGetZValueLength17
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTripletArray_RescueGetZValueLength17
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    XValues18
 * Signature: (J[FJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_XValues18
  (JNIEnv *, jobject, jlong, jfloatArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    YValues19
 * Signature: (J[FJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_YValues19
  (JNIEnv *, jobject, jlong, jfloatArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    ZValues20
 * Signature: (J[FJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_ZValues20
  (JNIEnv *, jobject, jlong, jfloatArray, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    IsOfType21
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_IsOfType21
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    IsRegular22
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_IsRegular22
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    IsCalculated23
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_IsCalculated23
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    ParentModel27
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTripletArray_ParentModel27
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    HasSplitNodes29
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_HasSplitNodes29
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    IsSplit30
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_IsSplit30
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    SetXYZCorner31
 * Signature: (JJJJFFF)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_SetXYZCorner31
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    ClearSplitNode32
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_ClearSplitNode32
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    ClearSplitNodes33
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_ClearSplitNodes33
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    IsLoaded34
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_IsLoaded34
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    Load35
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_Load35
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    FileTruncated36
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_FileTruncated36
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    Unload37
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_Unload37
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    HasChanged38
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueTripletArray_HasChanged38
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    MarkChanged39
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueTripletArray_MarkChanged39
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueTripletArray
 * Method:    Version40
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueTripletArray_Version40
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
