/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueGeobodyPart */

#ifndef _Included_org_Rescue_rjni_RescueGeobodyPart
#define _Included_org_Rescue_rjni_RescueGeobodyPart
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueGeobodyPart_R_TOMBSTONE
#define org_Rescue_rjni_RescueGeobodyPart_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueObject
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueObject 1L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueModel
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueModel 2L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueBlock
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueBlock 3L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueUnit
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueUnit 4L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueHorizon
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueSection
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueSection 6L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueBlockUnit
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueProperty
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueProperty 9L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePropertyGroup
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueWellbore
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueWellboreProperty
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueGrid
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueGrid 14L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueGridAxis
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueArray
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueArray 16L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueTripletArray
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueVertex
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueVertex 19L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueSurface
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueSurface 21L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueDoubletArray
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimVertex
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueEdgeSet
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimEdge
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLine
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNode
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueGeometry
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueSurfaceCell
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueWellboreSampling
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueWellboreSurface
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueWellboreCell
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueReferenceSurface
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueLookup
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueLookup 35L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueLookupItem
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueLookupString
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueLookupTable
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayDouble
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayByte
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayShort
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimLoop
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayFloat
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueMacroVolume
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueBitArray
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueColor
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueColor 48L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueHistory
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueHistory 49L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueHistoryObject
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueArray2dVector
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueArray3dVector
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueColorTable
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueColorTableList
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueGeobody
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueGeobodyPart
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueGeobodySurface
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueIJSurface
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueCellShape
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueEventDescr
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueLogicalOrder
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueFaultIntersection
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueWireframeStub
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineStub
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueWireframe
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueWireframeOwner
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayInt
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueGeometryUnit
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueReservoir
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescueGeobodyPart_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescueGeobodyPart_R_RescueDataContainer
#define org_Rescue_rjni_RescueGeobodyPart_R_RescueDataContainer 82L
/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    Create_RescueGeobodyPart0
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_Create_1RescueGeobodyPart0
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    Create_RescueGeobodyPart1
 * Signature: (IJFFJJFFJJFFJJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_Create_1RescueGeobodyPart1
  (JNIEnv *, jobject, jint, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    Create_RescueGeobodyPart2
 * Signature: (IJFFJJFFJJJJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_Create_1RescueGeobodyPart2
  (JNIEnv *, jobject, jint, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jlong, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    Create_RescueGeobodyPart3
 * Signature: (IJFFJJFFJJJJFJFJF)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_Create_1RescueGeobodyPart3
  (JNIEnv *, jobject, jint, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jlong, jlong, jfloat, jlong, jfloat, jlong, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    Create_RescueGeobodyPart4
 * Signature: (IJFFJJFFJJJJFJFFI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_Create_1RescueGeobodyPart4
  (JNIEnv *, jobject, jint, jlong, jfloat, jfloat, jlong, jlong, jfloat, jfloat, jlong, jlong, jlong, jlong, jfloat, jlong, jfloat, jfloat, jint);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    Delete_RescueGeobodyPart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_Delete_1RescueGeobodyPart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    Body6
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_Body6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    AddGeobodyVolume7
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_AddGeobodyVolume7
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    DropGeobodyVolume8
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_DropGeobodyVolume8
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    NthGeobodyVolume9
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_NthGeobodyVolume9
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    AddPropertyGroup10
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_AddPropertyGroup10
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    DeletePropertyGroup11
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_DeletePropertyGroup11
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    NthPropertyGroup12
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_NthPropertyGroup12
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    AddBlockUnit13
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_AddBlockUnit13
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    DropBlockUnit14
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_DropBlockUnit14
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    BlockUnitCount15
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_BlockUnitCount15
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    NthBlockUnit16
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_NthBlockUnit16
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    GridGeometry17
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_GridGeometry17
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    GeometryIdentifiedBy18
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_GeometryIdentifiedBy18
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    GeometryCount19
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_GeometryCount19
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    AddGeometry20
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_AddGeometry20
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    DropGeometry21
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_DropGeometry21
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    PropertyCount22
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_PropertyCount22
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    CountOfPropertyGroup23
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_CountOfPropertyGroup23
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    CountOfVolumes24
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_CountOfVolumes24
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    SetColor26
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_SetColor26
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    Color27
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_Color27
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    PropertyIdentifiedBy28
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_PropertyIdentifiedBy28
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    GeobodyVolumeIdentifiedBy29
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_GeobodyVolumeIdentifiedBy29
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    GeobodySurfaceIdentifiedBy30
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_GeobodySurfaceIdentifiedBy30
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    AnyFileTruncated31
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_AnyFileTruncated31
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueGeobodyPart
 * Method:    IsOfType32
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueGeobodyPart_IsOfType32
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
