/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueContext */

#ifndef _Included_org_Rescue_rjni_RescueContext
#define _Included_org_Rescue_rjni_RescueContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    SamePoint
 * Signature: (FFFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueContext_SamePoint
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    Create_RescueContext0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueContext_Create_1RescueContext0
  (JNIEnv *, jobject);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    RegisterProgressReporter1
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_RegisterProgressReporter1
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    SetAutoBackup2
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_SetAutoBackup2
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    SetFileNameManipulation3
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_SetFileNameManipulation3
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    CleanFromUnarchive4
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_CleanFromUnarchive4
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    SetLoadOnDemand5
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_SetLoadOnDemand5
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    DelayedPropertyLoad6
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueContext_DelayedPropertyLoad6
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    SetLoadOnDemand27
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_SetLoadOnDemand27
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    DelayedGeometryLoad8
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueContext_DelayedGeometryLoad8
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    RescueProgress9
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_RescueProgress9
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    GetLock10
 * Signature: (JLjava/lang/String;ZZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_RescueContext_GetLock10
  (JNIEnv *, jobject, jlong, jstring, jboolean, jboolean);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    ReleaseLock11
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_ReleaseLock11
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    CheckLock12
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueContext_CheckLock12
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    VetFileName13
 * Signature: (JLjava/lang/String;ZZ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_VetFileName13
  (JNIEnv *, jobject, jlong, jstring, jboolean, jboolean);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    FileVersion14
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueContext_FileVersion14
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    SoftwareVersion15
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueContext_SoftwareVersion15
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    LibraryVersion17
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueContext_LibraryVersion17
  (JNIEnv *, jclass);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    LibrarySubVersion18
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueContext_LibrarySubVersion18
  (JNIEnv *, jclass);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    TypeMarker19
 * Signature: (JLjava/lang/String;[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueContext_TypeMarker19
  (JNIEnv *, jobject, jlong, jstring, jbyteArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    FileTruncated20
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueContext_FileTruncated20
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    BinaryFlag21
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueContext_BinaryFlag21
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    ReadFileVersion22
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueContext_ReadFileVersion22
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    FileVersion23
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueContext_FileVersion23
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    NextId24
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueContext_NextId24
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    LastError25
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_Rescue_rjni_RescueContext_LastError25
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueContext
 * Method:    ClearError26
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueContext_ClearError26
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
