/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_Rescue_rjni_RescueProperty */

#ifndef _Included_org_Rescue_rjni_RescueProperty
#define _Included_org_Rescue_rjni_RescueProperty
#ifdef __cplusplus
extern "C" {
#endif
#undef org_Rescue_rjni_RescueProperty_R_TOMBSTONE
#define org_Rescue_rjni_RescueProperty_R_TOMBSTONE 0L
#undef org_Rescue_rjni_RescueProperty_R_RescueObject
#define org_Rescue_rjni_RescueProperty_R_RescueObject 1L
#undef org_Rescue_rjni_RescueProperty_R_RescueModel
#define org_Rescue_rjni_RescueProperty_R_RescueModel 2L
#undef org_Rescue_rjni_RescueProperty_R_RescueBlock
#define org_Rescue_rjni_RescueProperty_R_RescueBlock 3L
#undef org_Rescue_rjni_RescueProperty_R_RescueUnit
#define org_Rescue_rjni_RescueProperty_R_RescueUnit 4L
#undef org_Rescue_rjni_RescueProperty_R_RescueHorizon
#define org_Rescue_rjni_RescueProperty_R_RescueHorizon 5L
#undef org_Rescue_rjni_RescueProperty_R_RescueSection
#define org_Rescue_rjni_RescueProperty_R_RescueSection 6L
#undef org_Rescue_rjni_RescueProperty_R_RescueBlockUnit
#define org_Rescue_rjni_RescueProperty_R_RescueBlockUnit 7L
#undef org_Rescue_rjni_RescueProperty_R_RescueBlockUnitSide
#define org_Rescue_rjni_RescueProperty_R_RescueBlockUnitSide 8L
#undef org_Rescue_rjni_RescueProperty_R_RescueProperty
#define org_Rescue_rjni_RescueProperty_R_RescueProperty 9L
#undef org_Rescue_rjni_RescueProperty_R_RescuePropertyGroup
#define org_Rescue_rjni_RescueProperty_R_RescuePropertyGroup 10L
#undef org_Rescue_rjni_RescueProperty_R_RescueBlockUnitHorizonSurface
#define org_Rescue_rjni_RescueProperty_R_RescueBlockUnitHorizonSurface 11L
#undef org_Rescue_rjni_RescueProperty_R_RescueWellbore
#define org_Rescue_rjni_RescueProperty_R_RescueWellbore 12L
#undef org_Rescue_rjni_RescueProperty_R_RescueWellboreProperty
#define org_Rescue_rjni_RescueProperty_R_RescueWellboreProperty 13L
#undef org_Rescue_rjni_RescueProperty_R_RescueGrid
#define org_Rescue_rjni_RescueProperty_R_RescueGrid 14L
#undef org_Rescue_rjni_RescueProperty_R_RescueGridAxis
#define org_Rescue_rjni_RescueProperty_R_RescueGridAxis 15L
#undef org_Rescue_rjni_RescueProperty_R_RescueArray
#define org_Rescue_rjni_RescueProperty_R_RescueArray 16L
#undef org_Rescue_rjni_RescueProperty_R_RescueTripletArray
#define org_Rescue_rjni_RescueProperty_R_RescueTripletArray 17L
#undef org_Rescue_rjni_RescueProperty_R_RescueCoordinateSystemAxis
#define org_Rescue_rjni_RescueProperty_R_RescueCoordinateSystemAxis 18L
#undef org_Rescue_rjni_RescueProperty_R_RescueVertex
#define org_Rescue_rjni_RescueProperty_R_RescueVertex 19L
#undef org_Rescue_rjni_RescueProperty_R_RescueCoordinateSystem
#define org_Rescue_rjni_RescueProperty_R_RescueCoordinateSystem 20L
#undef org_Rescue_rjni_RescueProperty_R_RescueSurface
#define org_Rescue_rjni_RescueProperty_R_RescueSurface 21L
#undef org_Rescue_rjni_RescueProperty_R_RescueDoubletArray
#define org_Rescue_rjni_RescueProperty_R_RescueDoubletArray 22L
#undef org_Rescue_rjni_RescueProperty_R_RescueTrimVertex
#define org_Rescue_rjni_RescueProperty_R_RescueTrimVertex 23L
#undef org_Rescue_rjni_RescueProperty_R_RescueEdgeSet
#define org_Rescue_rjni_RescueProperty_R_RescueEdgeSet 24L
#undef org_Rescue_rjni_RescueProperty_R_RescueTrimEdge
#define org_Rescue_rjni_RescueProperty_R_RescueTrimEdge 25L
#undef org_Rescue_rjni_RescueProperty_R_RescuePolyLine
#define org_Rescue_rjni_RescueProperty_R_RescuePolyLine 26L
#undef org_Rescue_rjni_RescueProperty_R_RescuePolyLineNode
#define org_Rescue_rjni_RescueProperty_R_RescuePolyLineNode 27L
#undef org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeUV
#define org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeUV 28L
#undef org_Rescue_rjni_RescueProperty_R_RescueGeometry
#define org_Rescue_rjni_RescueProperty_R_RescueGeometry 29L
#undef org_Rescue_rjni_RescueProperty_R_RescueSurfaceCell
#define org_Rescue_rjni_RescueProperty_R_RescueSurfaceCell 30L
#undef org_Rescue_rjni_RescueProperty_R_RescueWellboreSampling
#define org_Rescue_rjni_RescueProperty_R_RescueWellboreSampling 31L
#undef org_Rescue_rjni_RescueProperty_R_RescueWellboreSurface
#define org_Rescue_rjni_RescueProperty_R_RescueWellboreSurface 32L
#undef org_Rescue_rjni_RescueProperty_R_RescueWellboreCell
#define org_Rescue_rjni_RescueProperty_R_RescueWellboreCell 33L
#undef org_Rescue_rjni_RescueProperty_R_RescueReferenceSurface
#define org_Rescue_rjni_RescueProperty_R_RescueReferenceSurface 34L
#undef org_Rescue_rjni_RescueProperty_R_RescueLookup
#define org_Rescue_rjni_RescueProperty_R_RescueLookup 35L
#undef org_Rescue_rjni_RescueProperty_R_RescueLookupItem
#define org_Rescue_rjni_RescueProperty_R_RescueLookupItem 36L
#undef org_Rescue_rjni_RescueProperty_R_RescueLookupString
#define org_Rescue_rjni_RescueProperty_R_RescueLookupString 37L
#undef org_Rescue_rjni_RescueProperty_R_RescueLookupTable
#define org_Rescue_rjni_RescueProperty_R_RescueLookupTable 38L
#undef org_Rescue_rjni_RescueProperty_R_RescueArrayDouble
#define org_Rescue_rjni_RescueProperty_R_RescueArrayDouble 39L
#undef org_Rescue_rjni_RescueProperty_R_RescueArrayByte
#define org_Rescue_rjni_RescueProperty_R_RescueArrayByte 40L
#undef org_Rescue_rjni_RescueProperty_R_RescueArrayShort
#define org_Rescue_rjni_RescueProperty_R_RescueArrayShort 41L
#undef org_Rescue_rjni_RescueProperty_R_RescueTrimLoop
#define org_Rescue_rjni_RescueProperty_R_RescueTrimLoop 42L
#undef org_Rescue_rjni_RescueProperty_R_RescueArrayFloat
#define org_Rescue_rjni_RescueProperty_R_RescueArrayFloat 43L
#undef org_Rescue_rjni_RescueProperty_R_RescueMacroVolume
#define org_Rescue_rjni_RescueProperty_R_RescueMacroVolume 44L
#undef org_Rescue_rjni_RescueProperty_R_RescueModelPropertyGroup
#define org_Rescue_rjni_RescueProperty_R_RescueModelPropertyGroup 45L
#undef org_Rescue_rjni_RescueProperty_R_RescueTimeStepGroup
#define org_Rescue_rjni_RescueProperty_R_RescueTimeStepGroup 46L
#undef org_Rescue_rjni_RescueProperty_R_RescueBitArray
#define org_Rescue_rjni_RescueProperty_R_RescueBitArray 47L
#undef org_Rescue_rjni_RescueProperty_R_RescueColor
#define org_Rescue_rjni_RescueProperty_R_RescueColor 48L
#undef org_Rescue_rjni_RescueProperty_R_RescueHistory
#define org_Rescue_rjni_RescueProperty_R_RescueHistory 49L
#undef org_Rescue_rjni_RescueProperty_R_RescueHistoryObject
#define org_Rescue_rjni_RescueProperty_R_RescueHistoryObject 50L
#undef org_Rescue_rjni_RescueProperty_R_RescueArray2dVector
#define org_Rescue_rjni_RescueProperty_R_RescueArray2dVector 51L
#undef org_Rescue_rjni_RescueProperty_R_RescueArray3dVector
#define org_Rescue_rjni_RescueProperty_R_RescueArray3dVector 52L
#undef org_Rescue_rjni_RescueProperty_R_RescueColorTable
#define org_Rescue_rjni_RescueProperty_R_RescueColorTable 53L
#undef org_Rescue_rjni_RescueProperty_R_RescueColorTableList
#define org_Rescue_rjni_RescueProperty_R_RescueColorTableList 54L
#undef org_Rescue_rjni_RescueProperty_R_RescueGeobody
#define org_Rescue_rjni_RescueProperty_R_RescueGeobody 55L
#undef org_Rescue_rjni_RescueProperty_R_RescueGeobodyPart
#define org_Rescue_rjni_RescueProperty_R_RescueGeobodyPart 56L
#undef org_Rescue_rjni_RescueProperty_R_RescueGeobodySurface
#define org_Rescue_rjni_RescueProperty_R_RescueGeobodySurface 57L
#undef org_Rescue_rjni_RescueProperty_R_RescueGeobodyVolume
#define org_Rescue_rjni_RescueProperty_R_RescueGeobodyVolume 58L
#undef org_Rescue_rjni_RescueProperty_R_RescueSurfaceToGrid
#define org_Rescue_rjni_RescueProperty_R_RescueSurfaceToGrid 59L
#undef org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeBUG
#define org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeBUG 60L
#undef org_Rescue_rjni_RescueProperty_R_RescueIJSurface
#define org_Rescue_rjni_RescueProperty_R_RescueIJSurface 61L
#undef org_Rescue_rjni_RescueProperty_R_RescueCellShape
#define org_Rescue_rjni_RescueProperty_R_RescueCellShape 62L
#undef org_Rescue_rjni_RescueProperty_R_RescueEventDescr
#define org_Rescue_rjni_RescueProperty_R_RescueEventDescr 63L
#undef org_Rescue_rjni_RescueProperty_R_RescueLogicalOrder
#define org_Rescue_rjni_RescueProperty_R_RescueLogicalOrder 64L
#undef org_Rescue_rjni_RescueProperty_R_RescueFaultIntersection
#define org_Rescue_rjni_RescueProperty_R_RescueFaultIntersection 65L
#undef org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeAvatar
#define org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeAvatar 66L
#undef org_Rescue_rjni_RescueProperty_R_RescueWireframeStub
#define org_Rescue_rjni_RescueProperty_R_RescueWireframeStub 67L
#undef org_Rescue_rjni_RescueProperty_R_RescuePolyLineStub
#define org_Rescue_rjni_RescueProperty_R_RescuePolyLineStub 68L
#undef org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeAvatarStub
#define org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeAvatarStub 69L
#undef org_Rescue_rjni_RescueProperty_R_RescueTrimVertexStub
#define org_Rescue_rjni_RescueProperty_R_RescueTrimVertexStub 70L
#undef org_Rescue_rjni_RescueProperty_R_RescueEdgeSetStub
#define org_Rescue_rjni_RescueProperty_R_RescueEdgeSetStub 71L
#undef org_Rescue_rjni_RescueProperty_R_RescueTrimLoopStub
#define org_Rescue_rjni_RescueProperty_R_RescueTrimLoopStub 72L
#undef org_Rescue_rjni_RescueProperty_R_RescueWireframe
#define org_Rescue_rjni_RescueProperty_R_RescueWireframe 73L
#undef org_Rescue_rjni_RescueProperty_R_RescueWireframeOwner
#define org_Rescue_rjni_RescueProperty_R_RescueWireframeOwner 74L
#undef org_Rescue_rjni_RescueProperty_R_RescueArrayInt
#define org_Rescue_rjni_RescueProperty_R_RescueArrayInt 75L
#undef org_Rescue_rjni_RescueProperty_R_RescueGeometryUnit
#define org_Rescue_rjni_RescueProperty_R_RescueGeometryUnit 76L
#undef org_Rescue_rjni_RescueProperty_R_RescueReservoir
#define org_Rescue_rjni_RescueProperty_R_RescueReservoir 77L
#undef org_Rescue_rjni_RescueProperty_R_RescueQuadrupletArray
#define org_Rescue_rjni_RescueProperty_R_RescueQuadrupletArray 78L
#undef org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeUVT
#define org_Rescue_rjni_RescueProperty_R_RescuePolyLineNodeUVT 79L
#undef org_Rescue_rjni_RescueProperty_R_RescueStairSteppedFault
#define org_Rescue_rjni_RescueProperty_R_RescueStairSteppedFault 80L
#undef org_Rescue_rjni_RescueProperty_R_RescueLogicalOrderEntry
#define org_Rescue_rjni_RescueProperty_R_RescueLogicalOrderEntry 81L
#undef org_Rescue_rjni_RescueProperty_R_RescueDataContainer
#define org_Rescue_rjni_RescueProperty_R_RescueDataContainer 82L
#undef org_Rescue_rjni_RescueProperty_FRONT
#define org_Rescue_rjni_RescueProperty_FRONT 0L
#undef org_Rescue_rjni_RescueProperty_BACK
#define org_Rescue_rjni_RescueProperty_BACK 1L
#undef org_Rescue_rjni_RescueProperty_BOTH
#define org_Rescue_rjni_RescueProperty_BOTH 2L
#undef org_Rescue_rjni_RescueProperty_NA
#define org_Rescue_rjni_RescueProperty_NA 3L
#undef org_Rescue_rjni_RescueProperty_CELL_CENTERED
#define org_Rescue_rjni_RescueProperty_CELL_CENTERED 0L
#undef org_Rescue_rjni_RescueProperty_FACE_CENTERED
#define org_Rescue_rjni_RescueProperty_FACE_CENTERED 1L
#undef org_Rescue_rjni_RescueProperty_NODE_CENTERED
#define org_Rescue_rjni_RescueProperty_NODE_CENTERED 2L
#undef org_Rescue_rjni_RescueProperty_I1_FACE
#define org_Rescue_rjni_RescueProperty_I1_FACE 3L
#undef org_Rescue_rjni_RescueProperty_I2_FACE
#define org_Rescue_rjni_RescueProperty_I2_FACE 4L
#undef org_Rescue_rjni_RescueProperty_J1_FACE
#define org_Rescue_rjni_RescueProperty_J1_FACE 5L
#undef org_Rescue_rjni_RescueProperty_J2_FACE
#define org_Rescue_rjni_RescueProperty_J2_FACE 6L
#undef org_Rescue_rjni_RescueProperty_K1_FACE
#define org_Rescue_rjni_RescueProperty_K1_FACE 7L
#undef org_Rescue_rjni_RescueProperty_K2_FACE
#define org_Rescue_rjni_RescueProperty_K2_FACE 8L
/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty0
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IF[FI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty0
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jfloat, jfloatArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty1
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;II[II)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty1
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jint, jintArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty2
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJB[BI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty2
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jlong, jbyte, jbyteArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty3
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJC[CI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty3
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jlong, jchar, jcharArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty4
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILorg/Rescue/rjni/Rescue2dVector;[Lorg/Rescue/rjni/Rescue2dVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty4
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jobject, jobjectArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty5
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILorg/Rescue/rjni/Rescue3dVector;[Lorg/Rescue/rjni/Rescue3dVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty5
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jobject, jobjectArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty6
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IF[FIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty6
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jfloat, jfloatArray, jint, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty7
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;II[IIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty7
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jint, jintArray, jint, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty8
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJB[BIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty8
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jlong, jbyte, jbyteArray, jint, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty9
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJC[CIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty9
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jlong, jchar, jcharArray, jint, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty10
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILorg/Rescue/rjni/Rescue2dVector;[Lorg/Rescue/rjni/Rescue2dVector;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty10
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jobject, jobjectArray, jint, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty11
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILorg/Rescue/rjni/Rescue3dVector;[Lorg/Rescue/rjni/Rescue3dVector;IJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty11
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jobject, jobjectArray, jint, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty12
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;F[FI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty12
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jfloat, jfloatArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty13
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;I[II)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty13
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jint, jintArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty14
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;JB[BI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty14
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jlong, jbyte, jbyteArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty15
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;JC[CI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty15
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jlong, jchar, jcharArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty16
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/Rescue/rjni/Rescue2dVector;[Lorg/Rescue/rjni/Rescue2dVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty16
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jobject, jobjectArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty17
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/Rescue/rjni/Rescue3dVector;[Lorg/Rescue/rjni/Rescue3dVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty17
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jobject, jobjectArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty18
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IF[FI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty18
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jstring, jint, jfloat, jfloatArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty19
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;II[II)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty19
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jstring, jint, jint, jintArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty20
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJB[BI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty20
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jstring, jint, jlong, jbyte, jbyteArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty21
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;IJC[CI)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty21
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jstring, jint, jlong, jchar, jcharArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty22
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILorg/Rescue/rjni/Rescue2dVector;[Lorg/Rescue/rjni/Rescue2dVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty22
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jstring, jint, jobject, jobjectArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Create_RescueProperty23
 * Signature: (JJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;ILorg/Rescue/rjni/Rescue3dVector;[Lorg/Rescue/rjni/Rescue3dVector;I)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Create_1RescueProperty23
  (JNIEnv *, jobject, jlong, jlong, jstring, jstring, jstring, jint, jobject, jobjectArray, jint);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Delete_RescueProperty
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueProperty_Delete_1RescueProperty
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    ParentBlockUnit19
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_ParentBlockUnit19
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    ParentGeobodyPart20
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_ParentGeobodyPart20
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    ParentSurface21
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_ParentSurface21
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    ParentIJSurface22
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_ParentIJSurface22
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    TriangulatedSurface23
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueProperty_TriangulatedSurface23
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    TrimLoopCount24
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_TrimLoopCount24
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    NthTrimLoop25
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_NthTrimLoop25
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    HowApplies26
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueProperty_HowApplies26
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    PropertyAttachedTo27
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_Rescue_rjni_RescueProperty_PropertyAttachedTo27
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    AddTrimLoop28
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueProperty_AddTrimLoop28
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Container29
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Container29
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    RelinkTrimLoops29
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueProperty_RelinkTrimLoops29
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Data30
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Data30
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    Geometry31
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_Geometry31
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    SetColorTable32
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueProperty_SetColorTable32
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    ColorTable33
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_Rescue_rjni_RescueProperty_ColorTable33
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    AnyFileTruncated34
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueProperty_AnyFileTruncated34
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    IsNamed35
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueProperty_IsNamed35
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    TestLock36
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueProperty_TestLock36
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    SetLock37
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueProperty_SetLock37
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    ResetLock38
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_Rescue_rjni_RescueProperty_ResetLock38
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_Rescue_rjni_RescueProperty
 * Method:    IsOfType39
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_org_Rescue_rjni_RescueProperty_IsOfType39
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
